import { Pool } from 'pg';
let _pool: Pool | null = null;
export function getPool(): Pool {
  if (!_pool) _pool = new Pool({ connectionString: process.env.DATABASE_URL, ssl: process.env.DATABASE_SSL === 'true' ? { rejectUnauthorized: false } : undefined, max: 10, idleTimeoutMillis: 30000 });
  return _pool;
}
export async function query<T = Record<string, unknown>>(sql: string, values?: unknown[]): Promise<T[]> {
  await ensureInit(); const result = await getPool().query(sql, values); return result.rows as T[];
}
export async function queryOne<T = Record<string, unknown>>(sql: string, values?: unknown[]): Promise<T | undefined> {
  const rows = await query<T>(sql, values); return rows[0];
}
export async function execute(sql: string, values?: unknown[]): Promise<number> {
  await ensureInit(); const result = await getPool().query(sql, values); return result.rowCount ?? 0;
}
let _initialized = false;
async function ensureInit() { if (_initialized) return; _initialized = true; await initSchema(); }

export async function initSchema() {
  const pool = getPool();
  await pool.query(`
    CREATE TABLE IF NOT EXISTS users (id SERIAL PRIMARY KEY, name TEXT NOT NULL, email TEXT NOT NULL UNIQUE, company TEXT, role TEXT, industry TEXT, team_size TEXT, linkedin TEXT, bio TEXT, status TEXT NOT NULL DEFAULT 'active', is_admin BOOLEAN NOT NULL DEFAULT FALSE, joined_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), last_login TIMESTAMPTZ);
    CREATE TABLE IF NOT EXISTS otp_codes (id SERIAL PRIMARY KEY, email TEXT NOT NULL, code TEXT NOT NULL, purpose TEXT NOT NULL DEFAULT 'login', expires_at TIMESTAMPTZ NOT NULL, used BOOLEAN NOT NULL DEFAULT FALSE, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
    CREATE TABLE IF NOT EXISTS assessments (id SERIAL PRIMARY KEY, user_id INTEGER NOT NULL REFERENCES users(id), team_name TEXT NOT NULL DEFAULT 'My Team', industry TEXT, assessment_date DATE NOT NULL DEFAULT CURRENT_DATE, notes TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
    CREATE TABLE IF NOT EXISTS assessment_collaborators (id SERIAL PRIMARY KEY, assessment_id INTEGER NOT NULL REFERENCES assessments(id) ON DELETE CASCADE, user_id INTEGER NOT NULL REFERENCES users(id), invited_by INTEGER NOT NULL REFERENCES users(id), invited_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), UNIQUE(assessment_id, user_id));
    CREATE TABLE IF NOT EXISTS assessment_emb (id SERIAL PRIMARY KEY, assessment_id INTEGER NOT NULL REFERENCES assessments(id) ON DELETE CASCADE, pivot_num INTEGER NOT NULL, pivot_name TEXT NOT NULL, capability TEXT NOT NULL, l1_criteria TEXT, l2_criteria TEXT, l3_criteria TEXT, current_level TEXT DEFAULT 'L1', score_icon TEXT DEFAULT 'diamond', evidence TEXT, gap_notes TEXT, sort_order INTEGER DEFAULT 0);
    CREATE TABLE IF NOT EXISTS assessment_business_drivers (id SERIAL PRIMARY KEY, assessment_id INTEGER NOT NULL REFERENCES assessments(id) ON DELETE CASCADE, category TEXT NOT NULL DEFAULT 'Engineering Cost', driver_name TEXT NOT NULL DEFAULT 'New Driver', description TEXT, is_mandatory BOOLEAN NOT NULL DEFAULT FALSE, considerations TEXT, notes TEXT, sort_order INTEGER DEFAULT 0);
    CREATE TABLE IF NOT EXISTS assessment_benchmarks (id SERIAL PRIMARY KEY, assessment_id INTEGER NOT NULL REFERENCES assessments(id) ON DELETE CASCADE, pillar TEXT NOT NULL, kpi_name TEXT NOT NULL, unit TEXT, target_value TEXT, current_value TEXT, status TEXT NOT NULL DEFAULT 'pending', notes TEXT, sort_order INTEGER DEFAULT 0, weight DECIMAL DEFAULT 0, definition TEXT, sub_category TEXT);
    CREATE TABLE IF NOT EXISTS assessment_scope (id SERIAL PRIMARY KEY, assessment_id INTEGER NOT NULL REFERENCES assessments(id) ON DELETE CASCADE, pillar TEXT NOT NULL, activity TEXT NOT NULL DEFAULT 'New Activity', required_level INTEGER NOT NULL DEFAULT 1, current_level INTEGER NOT NULL DEFAULT 1, gap INTEGER NOT NULL DEFAULT 0, notes TEXT, sort_order INTEGER DEFAULT 0, l1_guidance TEXT, l2_guidance TEXT, l3_guidance TEXT);
    CREATE TABLE IF NOT EXISTS assessment_kra (id SERIAL PRIMARY KEY, assessment_id INTEGER NOT NULL REFERENCES assessments(id) ON DELETE CASCADE, role_level TEXT NOT NULL DEFAULT 'Manager', person_name TEXT, kra_name TEXT NOT NULL DEFAULT 'New KRA', description TEXT, target TEXT, current TEXT, status TEXT NOT NULL DEFAULT 'not-started', notes TEXT, sort_order INTEGER DEFAULT 0, pillar TEXT);
    CREATE TABLE IF NOT EXISTS assessment_leadership (id SERIAL PRIMARY KEY, assessment_id INTEGER NOT NULL REFERENCES assessments(id) ON DELETE CASCADE, leader_name TEXT NOT NULL DEFAULT 'Leader', leader_role TEXT, skill_name TEXT NOT NULL, is_mandatory BOOLEAN NOT NULL DEFAULT FALSE, score INTEGER NOT NULL DEFAULT 0, notes TEXT, sort_order INTEGER DEFAULT 0, skill_category TEXT, detailed_skills TEXT);
    CREATE TABLE IF NOT EXISTS assessment_maturity_levels (id SERIAL PRIMARY KEY, assessment_id INTEGER NOT NULL REFERENCES assessments(id) ON DELETE CASCADE, factor_name TEXT NOT NULL, maturity_level INTEGER NOT NULL DEFAULT 1, ownership_level TEXT, skill_level TEXT, business_value TEXT, notes TEXT, sort_order INTEGER DEFAULT 0);
    CREATE TABLE IF NOT EXISTS talent_engineers (id SERIAL PRIMARY KEY, assessment_id INTEGER NOT NULL REFERENCES assessments(id) ON DELETE CASCADE, name TEXT NOT NULL DEFAULT 'New Engineer', employee_id TEXT, team TEXT, reports_to TEXT, job_title TEXT, level TEXT DEFAULT 'Mid', specialisation TEXT, employment TEXT DEFAULT 'Full-time', product_name TEXT, industry TEXT, ai_phase TEXT DEFAULT 'Phase 1', primary_stack TEXT, key_strengths TEXT, development_focus TEXT, training_recommendation TEXT, career_goal TEXT, manager_notes TEXT, sort_order INTEGER DEFAULT 0);
    CREATE TABLE IF NOT EXISTS talent_skills (id SERIAL PRIMARY KEY, engineer_id INTEGER NOT NULL REFERENCES talent_engineers(id) ON DELETE CASCADE, section TEXT NOT NULL, category TEXT NOT NULL, skill_name TEXT NOT NULL, description TEXT, self_score INTEGER DEFAULT 0, manager_score INTEGER DEFAULT 0, target_score INTEGER DEFAULT 0, notes TEXT, sort_order INTEGER DEFAULT 0);
    CREATE TABLE IF NOT EXISTS skillset_context (id SERIAL PRIMARY KEY, assessment_id INTEGER NOT NULL REFERENCES assessments(id) ON DELETE CASCADE, field_name TEXT NOT NULL, field_value TEXT, field_group TEXT DEFAULT 'basics', sort_order INTEGER DEFAULT 0);
    CREATE TABLE IF NOT EXISTS skillset_items (id SERIAL PRIMARY KEY, assessment_id INTEGER NOT NULL REFERENCES assessments(id) ON DELETE CASCADE, section TEXT NOT NULL, category TEXT, item_name TEXT NOT NULL, description TEXT, importance TEXT, current_level TEXT, required_level TEXT, gap TEXT, notes TEXT, sort_order INTEGER DEFAULT 0);
    CREATE TABLE IF NOT EXISTS chat_usage (id SERIAL PRIMARY KEY, user_id INTEGER NOT NULL REFERENCES users(id), message_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
    CREATE INDEX IF NOT EXISTS chat_usage_user_time ON chat_usage(user_id, message_at);
    CREATE TABLE IF NOT EXISTS blog_posts (id SERIAL PRIMARY KEY, title TEXT NOT NULL, category TEXT, excerpt TEXT, body TEXT, emoji TEXT DEFAULT '📝', read_time INTEGER DEFAULT 4, status TEXT NOT NULL DEFAULT 'draft', author_name TEXT DEFAULT 'The Pivot Model', published_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
    CREATE TABLE IF NOT EXISTS whitepapers (id SERIAL PRIMARY KEY, title TEXT NOT NULL, category TEXT, description TEXT, icon TEXT DEFAULT '📄', pages INTEGER DEFAULT 1, access TEXT NOT NULL DEFAULT 'members', file_url TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
    CREATE TABLE IF NOT EXISTS leads (id SERIAL PRIMARY KEY, name TEXT NOT NULL, email TEXT NOT NULL, company TEXT NOT NULL, role TEXT, industry TEXT, linkedin TEXT, team_size TEXT, challenges TEXT, service TEXT, status TEXT NOT NULL DEFAULT 'new', source TEXT, submitted_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
    CREATE TABLE IF NOT EXISTS settings (key TEXT PRIMARY KEY, value TEXT, updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
  `);
  // Migrations for existing databases
  const migrations = [
    `ALTER TABLE assessment_business_drivers ADD COLUMN IF NOT EXISTS is_mandatory BOOLEAN NOT NULL DEFAULT FALSE`,
    `ALTER TABLE assessment_business_drivers ADD COLUMN IF NOT EXISTS considerations TEXT`,
    `ALTER TABLE assessment_benchmarks ADD COLUMN IF NOT EXISTS weight DECIMAL DEFAULT 0`,
    `ALTER TABLE assessment_benchmarks ADD COLUMN IF NOT EXISTS definition TEXT`,
    `ALTER TABLE assessment_benchmarks ADD COLUMN IF NOT EXISTS sub_category TEXT`,
    `ALTER TABLE assessment_scope ADD COLUMN IF NOT EXISTS l1_guidance TEXT`,
    `ALTER TABLE assessment_scope ADD COLUMN IF NOT EXISTS l2_guidance TEXT`,
    `ALTER TABLE assessment_scope ADD COLUMN IF NOT EXISTS l3_guidance TEXT`,
    `ALTER TABLE assessment_kra ADD COLUMN IF NOT EXISTS pillar TEXT`,
    `ALTER TABLE assessment_leadership ADD COLUMN IF NOT EXISTS skill_category TEXT`,
    `ALTER TABLE assessment_leadership ADD COLUMN IF NOT EXISTS detailed_skills TEXT`,
  ];
  for (const m of migrations) { try { await pool.query(m); } catch {} }
  await seedDefaults(pool);
}

async function seedDefaults(pool: Pool) {
  const { rows: ar } = await pool.query("SELECT id FROM users WHERE email = 'pivotrics@gmail.com'");
  if (ar.length === 0) await pool.query("INSERT INTO users (name, email, status, is_admin) VALUES ('Admin', 'pivotrics@gmail.com', 'active', TRUE)");
  const { rows: sr } = await pool.query('SELECT COUNT(*) AS c FROM settings');
  if (parseInt(sr[0].c) === 0) await pool.query(`INSERT INTO settings (key, value) VALUES ('site_name','The Pivot Model'),('chat_enabled','false'),('chat_api_key',''),('chat_system_prompt','You are a helpful assistant for The Pivot Model book. Answer questions about engineering team maturity, offshore operations, and the EMB framework only.'),('chat_limit_day','20'),('chat_limit_week','80'),('chat_limit_month','200'),('otp_enabled','true')`);
  const { rows: pr } = await pool.query('SELECT COUNT(*) AS c FROM blog_posts');
  if (parseInt(pr[0].c) === 0) {
    await pool.query(`INSERT INTO blog_posts (title,category,excerpt,emoji,read_time,status,published_at) VALUES ('Why Most Offshore Engineering Teams Stay at L1','Engineering Maturity','The L1 trap is real — and it''s not the offshore team''s fault.','🔒',4,'published',NOW()-INTERVAL '7 days'),('The AI Readiness Paradox for Offshore Teams','AI & Developer Tools','AI amplifies existing engineering maturity — it doesn''t create it.','🤖',5,'published',NOW()-INTERVAL '14 days'),('Captive vs Third-Party Offshore: The Decision Framework','Offshore Operations','Neither model is superior. The right choice depends on five factors.','🏗️',6,'published',NOW()-INTERVAL '21 days')`);
    await pool.query(`INSERT INTO whitepapers (title,category,description,icon,pages,access) VALUES ('The EMB Framework','Framework Reference','Complete Engineering Maturity Benchmark reference with all criteria and scoring rubrics.','📊',24,'members'),('AI Readiness for Offshore Teams','AI & Developer Tools','Navigating Phases 1, 2 and 3 of AI adoption in offshore engineering centres.','🤖',18,'members'),('The Offshore Team Scorecard','Tools & Templates','Quick self-assessment tool — score your team in under 20 minutes.','✅',8,'public')`);
  }
}

export async function getSetting(key: string): Promise<string | null> {
  const row = await queryOne<{ value: string }>('SELECT value FROM settings WHERE key = $1', [key]);
  return row?.value ?? null;
}
export async function setSetting(key: string, value: string): Promise<void> {
  await execute(`INSERT INTO settings (key,value,updated_at) VALUES ($1,$2,NOW()) ON CONFLICT (key) DO UPDATE SET value=EXCLUDED.value,updated_at=NOW()`, [key, value]);
}

export const EMB_TEMPLATE = [
  { pivot_num:1,pivot_name:'Operational Excellence',capability:'Code Quality & Review',l1_criteria:'Code is functional; basic reviews happen ad-hoc',l2_criteria:'Consistent PR reviews with quality gates; lint & static analysis in CI',l3_criteria:'Ownership culture; engineers proactively raise quality standards',sort_order:1},
  { pivot_num:1,pivot_name:'Operational Excellence',capability:'Testing Discipline',l1_criteria:'Manual testing primarily; unit tests sparse',l2_criteria:'Unit & integration tests standard; coverage tracked',l3_criteria:'TDD mindset; test coverage > 80%; performance & regression suites',sort_order:2},
  { pivot_num:1,pivot_name:'Operational Excellence',capability:'CI/CD & Build Pipeline',l1_criteria:'Manual or semi-automated deployments',l2_criteria:'Automated CI/CD; environments properly separated',l3_criteria:'Zero-downtime deploys; feature flags; automated rollback',sort_order:3},
  { pivot_num:1,pivot_name:'Operational Excellence',capability:'Incident & On-Call Management',l1_criteria:'Reactive; escalation dependent on single individuals',l2_criteria:'On-call rotation; post-mortems conducted',l3_criteria:'Blameless culture; SLOs/SLAs defined and tracked; proactive alerting',sort_order:4},
  { pivot_num:1,pivot_name:'Operational Excellence',capability:'Documentation Standards',l1_criteria:'Documentation sparse or outdated',l2_criteria:'APIs and systems documented; runbooks maintained',l3_criteria:'Living documentation culture; architecture decisions recorded',sort_order:5},
  { pivot_num:2,pivot_name:'Pace of Product Evolution',capability:'Sprint Velocity & Predictability',l1_criteria:'Sprints frequently miss targets; estimation inconsistent',l2_criteria:'Stable velocity; 80%+ sprint commitments met',l3_criteria:'Predictable delivery with clear capacity planning',sort_order:6},
  { pivot_num:2,pivot_name:'Pace of Product Evolution',capability:'Technical Debt Management',l1_criteria:'Debt accumulates unchecked; no tracking',l2_criteria:'Debt tracked and allocated budget in sprints',l3_criteria:'Proactive refactoring; debt ratio declining; architectural clarity',sort_order:7},
  { pivot_num:2,pivot_name:'Pace of Product Evolution',capability:'Feature Delivery Speed',l1_criteria:'High cycle time; long lead times',l2_criteria:'Reasonable lead times; cycle time tracked and improving',l3_criteria:'Lean flow; small batch sizes; continuous delivery',sort_order:8},
  { pivot_num:2,pivot_name:'Pace of Product Evolution',capability:'Innovation & Continuous Improvement',l1_criteria:'Reactive; no time for improvement',l2_criteria:'Regular retrospectives; process improvements implemented',l3_criteria:'Engineers drive innovation; experimentation encouraged',sort_order:9},
  { pivot_num:3,pivot_name:'Collaboration & Alignment',capability:'Stakeholder Communication',l1_criteria:'Communication reactive; status updates only when asked',l2_criteria:'Regular structured updates; blockers surfaced proactively',l3_criteria:'Engineers communicate business context; trusted partners to onshore',sort_order:10},
  { pivot_num:3,pivot_name:'Collaboration & Alignment',capability:'Cross-Team Collaboration',l1_criteria:'Siloed; minimal coordination outside own team',l2_criteria:'Regular cross-team sync; dependencies managed',l3_criteria:'Collaborative problem-solving; shared ownership across teams',sort_order:11},
  { pivot_num:3,pivot_name:'Collaboration & Alignment',capability:'Cultural Integration',l1_criteria:'Cultural gap significant; us-vs-them mentality',l2_criteria:'Cultural awareness growing; some integration initiatives',l3_criteria:'Genuinely integrated culture; offshore seen as equal partner',sort_order:12},
  { pivot_num:3,pivot_name:'Collaboration & Alignment',capability:'Knowledge Sharing',l1_criteria:'Knowledge siloed in individuals; no documentation culture',l2_criteria:'Regular knowledge sharing sessions; wikis maintained',l3_criteria:'Continuous learning culture; internal talks; mentoring programs',sort_order:13},
  { pivot_num:4,pivot_name:'Business Results',capability:'Business Impact Awareness',l1_criteria:'Engineers unaware of business metrics',l2_criteria:'Team understands product KPIs; can connect work to outcomes',l3_criteria:'Engineers drive business conversations; suggest product improvements',sort_order:14},
  { pivot_num:4,pivot_name:'Business Results',capability:'KRA Achievement',l1_criteria:'KRAs unclear or unmeasured',l2_criteria:'KRAs defined per role; tracked quarterly',l3_criteria:'KRAs tied to business OKRs; self-managed accountability',sort_order:15},
  { pivot_num:4,pivot_name:'Business Results',capability:'Customer Orientation',l1_criteria:'No direct customer interaction or feedback loop',l2_criteria:'Engineers exposed to customer feedback; user stories understood',l3_criteria:'Engineers participate in customer calls; empathy drives design',sort_order:16},
  { pivot_num:4,pivot_name:'Business Results',capability:'Strategic Contribution',l1_criteria:'Offshore purely execution; no input to strategy',l2_criteria:'Offshore contributes to technical roadmap',l3_criteria:'Offshore drives product innovation; strategic thought partner',sort_order:17},
  { pivot_num:5,pivot_name:'People & Talent',capability:'Hiring Quality',l1_criteria:'Reactive hiring; skills assessed informally',l2_criteria:'Structured interviews; defined scorecards; bar-raiser in process',l3_criteria:'Elite talent pipeline; offshore competes globally for top talent',sort_order:18},
  { pivot_num:5,pivot_name:'People & Talent',capability:'Retention & Growth',l1_criteria:'High attrition; no career framework',l2_criteria:'Career paths defined; mentoring present; attrition tracked',l3_criteria:'Low attrition; strong internal mobility; engineers actively growing',sort_order:19},
  { pivot_num:5,pivot_name:'People & Talent',capability:'Leadership Pipeline',l1_criteria:'No defined senior / staff / principal track offshore',l2_criteria:'Senior engineers visible; team leads emerging',l3_criteria:'Strong offshore leadership; directors and VPs developed internally',sort_order:20},
  { pivot_num:5,pivot_name:'People & Talent',capability:'AI & Tool Adoption',l1_criteria:'No AI tooling; awareness low',l2_criteria:'Copilot / AI tools adopted; productivity improving',l3_criteria:'AI-native workflows; engineers amplified 2x+ by tooling',sort_order:21},
];

export const DRIVER_TEMPLATE = [
  {category:'Engineering Cost',driver_name:'Investment Decision',is_mandatory:true,considerations:'* Data driven decision making (portfolio management)\n* Prioritize features & backlogs\n* Track ROI on investment in engineering activities',sort_order:1},
  {category:'Engineering Cost',driver_name:'Cost Advantage of Offshore Operation',is_mandatory:true,considerations:'* Target Operational Cost\n* Target for Total Cost of Product Ownership\n* Higher value-per-dollar / ROI',sort_order:2},
  {category:'Engineering Cost',driver_name:'Team Size / Headcount',is_mandatory:true,considerations:'* Source of budget (R&D Budget vs Customer Funded)\n* Headcount approval process\n* Goal Alignment & HC Forecasting\n* Talent & Skill Management\n* Offshore Factors',sort_order:3},
  {category:'Scale of Engineering Operations',driver_name:'Reason for Increasing Team Size',is_mandatory:false,considerations:'* New skills required to address architectural and technical complexities\n* Increase in System size & scope\n* Technical Liabilities',sort_order:4},
  {category:'Scale of Engineering Operations',driver_name:'Headcount & Staffing Plans',is_mandatory:true,considerations:'* Headcount planning & Projections\n* Talent Density & Specialization\n* Characteristics of work culture\n* Team structure\n* Sponsor from leadership to be identified\n* Communication plans with offshore teams',sort_order:5},
  {category:'Scale of Engineering Operations',driver_name:'Process, Structure & Well-Defined Roles',is_mandatory:true,considerations:'* Define and implement a process that is appropriate to the scale and complexity of the engineering operation\n* Evolve staffing strategies and well defined engineering roles as preparation to handle the additional scale.',sort_order:6},
  {category:'Scale of Engineering Operations',driver_name:'Leveraging Offshore Advantage',is_mandatory:true,considerations:'* Flexibility to scale the team and engineering operations as needed\n* Broader access to skilled talent across regions\n* Enhanced engineering capabilities through complementary benefits such as faster time-to-market and round-the-clock operations enabled by the offshore team',sort_order:7},
  {category:'Strategic Business Expansion',driver_name:'Centrally Located Engineering Operation',is_mandatory:true,considerations:'Either the complete engineering operation or at least the core of the engineering team is located in one main location.',sort_order:8},
  {category:'Strategic Business Expansion',driver_name:'Offshore Driven Strategic Expansion',is_mandatory:true,considerations:'When the product\'s business grows, challenges such as talent availability, geographic reach, and budget constraints may arise. These issues can be managed by relocating certain engineering operations to offshore locations.',sort_order:9},
];

export const BENCHMARK_TEMPLATE = [
  {pillar:'Operational Excellence',sub_category:'Performance / Product Stability',kpi_name:'Sprint Velocity',definition:'The average number of Story Points or work items a team completes per sprint. Goal is predictability over raw increase.',weight:0.1,unit:'pts/sprint',target_value:'±10% of Avg',sort_order:1},
  {pillar:'Operational Excellence',sub_category:'Performance / Product Stability',kpi_name:'Cycle Time',definition:'The time it takes for a work item to go from In Progress to Done.',weight:0.1,unit:'days',target_value:'≤ 4 days',sort_order:2},
  {pillar:'Operational Excellence',sub_category:'Performance / Product Stability',kpi_name:'Defect Escape Rate',definition:'The ratio of defects found in production to the total number of defects found. Goal is to find defects before release.',weight:0.1,unit:'%',target_value:'≤ 5%',sort_order:3},
  {pillar:'Operational Excellence',sub_category:'Performance / Product Stability',kpi_name:'Deployment Frequency',definition:'How often the team successfully releases changes to production.',weight:0.2,unit:'per week',target_value:'≥ 1/week',sort_order:4},
  {pillar:'Operational Excellence',sub_category:'Performance / Product Stability',kpi_name:'Code Maintainability Score',definition:'A score calculated by static analysis tools based on complexity, duplication, and coverage.',weight:0.1,unit:'score',target_value:'≥ 8/10',sort_order:5},
  {pillar:'Operational Excellence',sub_category:'Performance / Product Stability',kpi_name:'Change Failure Rate (CFR)',definition:'The percentage of deployments that result in a service impairment requiring remediation.',weight:0.2,unit:'%',target_value:'≤ 1%',sort_order:6},
  {pillar:'Operational Excellence',sub_category:'Performance / Product Stability',kpi_name:'Mean Time to Recovery (MTR)',definition:'The average time to restore service after a production incident.',weight:0.2,unit:'mins',target_value:'≤ 15 mins',sort_order:7},
  {pillar:'Operational Excellence',sub_category:'Commitment to AI and Automation for Efficiency',kpi_name:'Extent of AI Usage in coding and testing',definition:'The percentage of code/tests generated or refactored by AI tools compared to total.',weight:0.3,unit:'%',target_value:'≥ 25%',sort_order:8},
  {pillar:'Operational Excellence',sub_category:'Commitment to AI and Automation for Efficiency',kpi_name:'Effectiveness of QA Automation',definition:'The percentage of test coverage provided by automated tests and reduction in manual testing time.',weight:0.4,unit:'%',target_value:'≥ 85% Coverage',sort_order:9},
  {pillar:'Operational Excellence',sub_category:'Commitment to AI and Automation for Efficiency',kpi_name:'Success Rate of Release & Deployment Automation',definition:'The percentage of releases/deployments that complete automatically without manual intervention.',weight:0.3,unit:'%',target_value:'≥ 97%',sort_order:10},
  {pillar:'Operational Excellence',sub_category:'Continuous Improvement in Engineering Capabilities',kpi_name:'Progress Measured through Knowledge-Skill Matrix',definition:'The percentage increase in average skill level and critical skills covered by the team.',weight:0.3,unit:'%',target_value:'≥ 10% increase/qtr',sort_order:11},
  {pillar:'Operational Excellence',sub_category:'Continuous Improvement in Engineering Capabilities',kpi_name:'Optimal Resource Utilization',definition:'The percentage of engineer time spent on planned value-add work versus unplanned work.',weight:0.25,unit:'%',target_value:'≥ 95%',sort_order:12},
  {pillar:'Operational Excellence',sub_category:'Continuous Improvement in Engineering Capabilities',kpi_name:'Experimentation and Innovation Adoption',definition:'The number of prototypes, PoCs, or new technologies successfully integrated into production.',weight:0.2,unit:'count/qtr',target_value:'≥ 2/qtr',sort_order:13},
  {pillar:'Operational Excellence',sub_category:'Continuous Improvement in Engineering Capabilities',kpi_name:'Employee Retention Rates',definition:'The percentage of engineering staff retained over a 12-month period.',weight:0.25,unit:'%',target_value:'≥ 90%',sort_order:14},
  {pillar:'Operational Excellence',sub_category:'Quality of Work: Reliability and User Experience',kpi_name:'High System Availability',definition:'The percentage of time the system is operational and usable by customers.',weight:0.4,unit:'%',target_value:'≥ 99.95%',sort_order:15},
  {pillar:'Operational Excellence',sub_category:'Quality of Work: Reliability and User Experience',kpi_name:'Service-Level Objectives (SLOs)',definition:'Internal targets for measurable service characteristics (latency, throughput, error rate).',weight:0.35,unit:'%',target_value:'≥ 99%',sort_order:16},
  {pillar:'Operational Excellence',sub_category:'Quality of Work: Reliability and User Experience',kpi_name:'Customer Reported Incidents',definition:'The volume of unique, critical bugs or incidents reported by customers per month.',weight:0.25,unit:'count/month',target_value:'≤ 5/month',sort_order:17},
  {pillar:'Pace of Product Evolution',sub_category:'Speed and Efficiency of Product Development',kpi_name:'Release Cadence',definition:'How often a product or feature is deployed to the user environment.',weight:0.2,unit:'per month',target_value:'≥ 1/month',sort_order:18},
  {pillar:'Pace of Product Evolution',sub_category:'Speed and Efficiency of Product Development',kpi_name:'Cycle Time for New Features',definition:'The average time from first commit to production release for a feature.',weight:0.3,unit:'days',target_value:'≤ 4 days',sort_order:19},
  {pillar:'Pace of Product Evolution',sub_category:'Speed and Efficiency of Product Development',kpi_name:'Codebase Complexity Score (CCS)',definition:'An aggregate score (1-10) from static analysis of code cleanliness, test coverage, and architecture.',weight:0.2,unit:'score',target_value:'≥ 8/10',sort_order:20},
  {pillar:'Pace of Product Evolution',sub_category:'Speed and Efficiency of Product Development',kpi_name:'Rework Percentage',definition:'The percentage of work that must be reopened or revisited within the same dev cycle.',weight:0.15,unit:'%',target_value:'≤ 10%',sort_order:21},
  {pillar:'Pace of Product Evolution',sub_category:'Speed and Efficiency of Product Development',kpi_name:'Blocker Resolution Rate',definition:'The percentage of blocking issues resolved within a target time frame (e.g., 4 business hours).',weight:0.15,unit:'%',target_value:'≥ 95%',sort_order:22},
  {pillar:'Pace of Product Evolution',sub_category:'Roadmap Execution and Strategic Alignment',kpi_name:'Roadmap Adherence',definition:'The percentage of committed roadmap items completed within the targeted timeframe.',weight:0.3,unit:'%',target_value:'≥ 85%',sort_order:23},
  {pillar:'Pace of Product Evolution',sub_category:'Roadmap Execution and Strategic Alignment',kpi_name:'Feature Completion Rate',definition:'The percentage of features started and successfully completed within a sprint/period.',weight:0.25,unit:'%',target_value:'≥ 90%',sort_order:24},
  {pillar:'Pace of Product Evolution',sub_category:'Roadmap Execution and Strategic Alignment',kpi_name:'Lead Time for Changes',definition:'The time from first commit to running successfully in production (core DORA metric).',weight:0.35,unit:'days',target_value:'≤ 3 days',sort_order:25},
  {pillar:'Pace of Product Evolution',sub_category:'Roadmap Execution and Strategic Alignment',kpi_name:'Backlog Health',definition:'A score based on the percentage of backlog items that are sized, prioritized, and ready.',weight:0.1,unit:'%',target_value:'≥ 75% ready',sort_order:26},
  {pillar:'Pace of Product Evolution',sub_category:'Customer-Driven Innovation and Market Responsiveness',kpi_name:'Customer-Driven Enhancement Ratio',definition:'The percentage of new features originating from direct customer feedback or usage data.',weight:0.35,unit:'%',target_value:'≥ 65%',sort_order:27},
  {pillar:'Pace of Product Evolution',sub_category:'Customer-Driven Innovation and Market Responsiveness',kpi_name:'Customer Satisfaction with New Features',definition:'A score measuring customer happiness with recently released features.',weight:0.4,unit:'score',target_value:'≥ 8.5/10',sort_order:28},
  {pillar:'Pace of Product Evolution',sub_category:'Customer-Driven Innovation and Market Responsiveness',kpi_name:'Beta Feature Adoption Rate',definition:'The percentage of eligible users who actively engage with a new feature during beta testing.',weight:0.25,unit:'%',target_value:'≥ 15%',sort_order:29},
  {pillar:'Alignment',sub_category:'Cross Team Collaboration Efficiency',kpi_name:'Engineering-to-Product Alignment Score',definition:'A survey score on how well engineering roadmap aligns with product vision and business goals.',weight:0.15,unit:'score',target_value:'≥ 4.5/5',sort_order:30},
  {pillar:'Alignment',sub_category:'Cross Team Collaboration Efficiency',kpi_name:'Cross-Team Dependency Resolution Time',definition:'The average time to resolve an issue requiring input from two or more teams.',weight:0.25,unit:'days',target_value:'≤ 2 days',sort_order:31},
  {pillar:'Alignment',sub_category:'Cross Team Collaboration Efficiency',kpi_name:'Decision-Making Speed for Feature Approvals',definition:'The average time from feature proposal to final Go/No-Go approval.',weight:0.2,unit:'days',target_value:'≤ 3 days',sort_order:32},
  {pillar:'Alignment',sub_category:'Cross Team Collaboration Efficiency',kpi_name:'Stakeholder Satisfaction Scores',definition:'An aggregate score from key stakeholders on effectiveness of collaboration.',weight:0.15,unit:'score',target_value:'≥ 4.0/5',sort_order:33},
  {pillar:'Alignment',sub_category:'Cross Team Collaboration Efficiency',kpi_name:'Collaboration Frequency',definition:'The average number of value-driving interactions between team members and stakeholders per week.',weight:0.1,unit:'per week',target_value:'≥ 5/week',sort_order:34},
  {pillar:'Alignment',sub_category:'Cross Team Collaboration Efficiency',kpi_name:'Alignment with Shared OKRs',definition:'The percentage of shared objectives successfully met at end of cycle.',weight:0.15,unit:'%',target_value:'≥ 80%',sort_order:35},
  {pillar:'Alignment',sub_category:'Assessing Responsiveness and Adaptability',kpi_name:'Cycle Time for Decision-Making',definition:'The average time from identifying the need for a major decision to making and communicating it.',weight:0.4,unit:'days',target_value:'≤ 2 days',sort_order:36},
  {pillar:'Alignment',sub_category:'Assessing Responsiveness and Adaptability',kpi_name:'Roadmap Commitment Fulfilment',definition:'The percentage of work planned for a period that is successfully delivered.',weight:0.35,unit:'%',target_value:'≥ 85%',sort_order:37},
  {pillar:'Alignment',sub_category:'Assessing Responsiveness and Adaptability',kpi_name:'Feedback Incorporation Rates',definition:'The percentage of validated feedback added to the backlog and scheduled for implementation.',weight:0.25,unit:'%',target_value:'≥ 70%',sort_order:38},
  {pillar:'Alignment',sub_category:'Evaluating Engagement and Operational Cohesion',kpi_name:'Engagement in Cross-Functional Initiatives',definition:'Percentage of engineering team members actively contributing to shared non-feature work.',weight:0.25,unit:'%',target_value:'≥ 40%',sort_order:39},
  {pillar:'Alignment',sub_category:'Evaluating Engagement and Operational Cohesion',kpi_name:'Vendor Performance Ratings',definition:'An aggregate score on quality, timeliness, and cost-effectiveness of vendor work.',weight:0.25,unit:'score',target_value:'≥ 4.5/5',sort_order:40},
  {pillar:'Alignment',sub_category:'Evaluating Engagement and Operational Cohesion',kpi_name:'Net Promoter Score (NPS) for Internal Collaboration',definition:'NPS from internal stakeholders on how likely they are to recommend working with Engineering.',weight:0.5,unit:'score',target_value:'≥ 50',sort_order:41},
  {pillar:'Business Results Focused',sub_category:'Measuring Engineering-Driven Business Growth',kpi_name:'Percentage of New Features with Positive ROI',definition:'The percentage of features released in the last 12-18 months showing positive financial return.',weight:0.25,unit:'%',target_value:'≥ 70%',sort_order:42},
  {pillar:'Business Results Focused',sub_category:'Measuring Engineering-Driven Business Growth',kpi_name:'Business Impact of New Product Innovations',definition:'The percentage of revenue or profit derived from features released in the last 12-18 months.',weight:0.1,unit:'%',target_value:'≥ 25%',sort_order:43},
  {pillar:'Business Results Focused',sub_category:'Measuring Engineering-Driven Business Growth',kpi_name:'Feature Adoption Rate',definition:'The percentage of target users that use a new feature at least once within a defined period.',weight:0.1,unit:'%',target_value:'≥ 40%',sort_order:44},
  {pillar:'Business Results Focused',sub_category:'Measuring Engineering-Driven Business Growth',kpi_name:'Customer Retention Impact',definition:'The correlation between usage of new features and retention rate of customer cohorts.',weight:0.2,unit:'%',target_value:'≥ 5% higher retention',sort_order:45},
  {pillar:'Business Results Focused',sub_category:'Measuring Engineering-Driven Business Growth',kpi_name:'Cost Savings from Automation and Process Optimizations',definition:'The annualized dollar amount saved due to internal engineering efforts.',weight:0.1,unit:'USD/year',target_value:'≥ $100k/year',sort_order:46},
  {pillar:'Business Results Focused',sub_category:'Measuring Engineering-Driven Business Growth',kpi_name:'Cost of Quality (COQ)',definition:'The total cost as percentage of engineering spend on Prevention + Appraisal + Failure.',weight:0.15,unit:'%',target_value:'≤ 15% of spend',sort_order:47},
  {pillar:'Business Results Focused',sub_category:'Measuring Engineering-Driven Business Growth',kpi_name:'Technical Debt Ratio (TDR)',definition:'The percentage of time spent on planned maintenance and refactoring vs. new feature development.',weight:0.1,unit:'%',target_value:'≥ 20%',sort_order:48},
  {pillar:'Business Results Focused',sub_category:'Impact on Customers / End Users',kpi_name:'Time-to-Value (TTV)',definition:'The average time from feature release to when customers realize its core benefit.',weight:0.3,unit:'days',target_value:'≤ 2 days',sort_order:49},
  {pillar:'Business Results Focused',sub_category:'Impact on Customers / End Users',kpi_name:'Customer Commitment Success Rate',definition:'The percentage of major features delivered meeting the original agreed-upon deadline.',weight:0.25,unit:'%',target_value:'≥ 90%',sort_order:50},
  {pillar:'Business Results Focused',sub_category:'Impact on Customers / End Users',kpi_name:'Customer Satisfaction Score',definition:'The overall CSAT or NPS result from customer surveys.',weight:0.25,unit:'score',target_value:'≥ 8.5/10',sort_order:51},
  {pillar:'Business Results Focused',sub_category:'Impact on Customers / End Users',kpi_name:'Feature Stickiness / Health Score',definition:'The percentage of users who use a new feature more than three times in a given period.',weight:0.2,unit:'%',target_value:'≥ 15%',sort_order:52},
];

export const SCOPE_TEMPLATE = [
  {pillar:'Product Enhancement & Sustenance',activity:'Feature Development',required_level:2,l1_guidance:'The parent organization needs to provide detailed requirements for the features and also provide closer oversight to monitor execution.',l2_guidance:'The team designs and delivers complete features from high-level requirements with minimal supervision.',l3_guidance:'The team co-owns the responsibility to conceptualize the product in collaboration with internal and external stakeholders.',sort_order:1},
  {pillar:'Product Enhancement & Sustenance',activity:'Product Maintenance',required_level:3,l1_guidance:'The team will be responsible for reactive activities such as L1/L2/L3 support and fix minor defects.',l2_guidance:'The team is capable to analyze complex product issues and prepare proactive plans to make patches/releases.',l3_guidance:'Lead definition of patch and maintenance releases by prioritizing defects, technical, and feature debt. Manage all customer escalations.',sort_order:2},
  {pillar:'Product Enhancement & Sustenance',activity:'Solution Architecture, Deployment and Operations',required_level:3,l1_guidance:'Focus on operational aspects such as devops, database administration, cloud deployment, integration and scheduled maintenance.',l2_guidance:'The team monitors operational metrics and takes proactive steps to ensure the product meets functional and reliability targets.',l3_guidance:'Design architecture for global or regional deployments, including any negotiations with third-party providers for solution components.',sort_order:3},
  {pillar:'Product Enhancement & Sustenance',activity:'Professional Services',required_level:3,l1_guidance:'Work behind the scenes to make product configuration as per requirement provided by the parent organization.',l2_guidance:'The team will interact with customers to document the requirements, prepare the rollout plan and independently deliver any customizations.',l3_guidance:'Participate across customer engagement cycle. This includes presales, consultation for customers, implementation and configuration services.',sort_order:4},
  {pillar:'Thought Leadership',activity:'Measurable Effect on Business Outcome',required_level:2,l1_guidance:'The team is not expected to make any direct impact on business outcomes, except for offering operational cost advantage.',l2_guidance:'The team will own responsibilities that will directly impact product revenue cycles by delivering predictable results with minimal management oversight.',l3_guidance:'The team is active across the entire product lifecycle (including marketing and sales) to support efforts to create and sustain revenue streams.',sort_order:5},
  {pillar:'Thought Leadership',activity:'Product Roadmap - Feedback Loop',required_level:2,l1_guidance:'Support collection of data regarding product defects and operational challenges, which then supports decision-making by leadership team.',l2_guidance:'The team plays a critical role in managing requirements backlog (defects, technical debt, and feature debt) and ideas for incremental innovation.',l3_guidance:'Identify and prioritize release candidates by collaborating with internal and external stakeholders to ensure they align with business priorities.',sort_order:6},
  {pillar:'Thought Leadership',activity:'Culture of Excellence',required_level:3,l1_guidance:'Demonstrates the technical skills required to complete assigned engineering tasks and apply established best practices as directed.',l2_guidance:'Equipped with a product mindset, domain expertise, and technical skills, the team is able to deliver the product with very minimal guidance.',l3_guidance:'Demonstrates leadership skills to manage the full product lifecycle, represents the organization externally and publish whitepapers.',sort_order:7},
  {pillar:'Thought Leadership',activity:'Improve Customer Satisfaction',required_level:3,l1_guidance:'There is no direct impact on customer satisfaction. They can reduce the chance of dissatisfaction stemming from bugs or missed deadlines.',l2_guidance:'The team will ensure the product\'s features and its performance will offer the business advantages that end users expect.',l3_guidance:'Proactively identify and adopt new domain trends and evolving technology to ensure product remains highly relevant to customers.',sort_order:8},
  {pillar:'Business Result Focused',activity:'Impact on Business Profitability',required_level:2,l1_guidance:'Operational cost advantage will impact the bottomline, despite the additional bandwidth required for management oversight.',l2_guidance:'By reducing total cost of product ownership (TCO), the team offers significant bottom line advantage to improve profitability.',l3_guidance:'The team will play a key role in ensuring maximum ROI from investment in engineering efforts including feature development or ongoing R&D effort.',sort_order:9},
  {pillar:'Business Result Focused',activity:'Higher Share of Market',required_level:2,l1_guidance:'The team cannot be expected offer any advantage in terms of supporting the product\'s market share.',l2_guidance:'The team can support growth of the business by improving the time to market advantages.',l3_guidance:'Beyond core engineering, the team will leverage industry and customer insights to develop superior product capabilities that capture market share.',sort_order:10},
  {pillar:'Business Result Focused',activity:'Higher Customer Satisfaction',required_level:3,l1_guidance:'Disciplined execution and strict adherence to the engineering process will ensure consistent and high-quality deliverables.',l2_guidance:'Beyond delivering defect-free products, the team will ensure the product serves the intended business purpose of the end user.',l3_guidance:'Provide valuable consulting to customers and end users, regarding how the product can be leveraged to enhance or optimize the business.',sort_order:11},
  {pillar:'Customer Satisfaction',activity:'Incremental Innovations',required_level:2,l1_guidance:'There is no contribution expected in this regard.',l2_guidance:'The knowledge gained from product release cycles and operational issues should enable the team to generate ideas for incremental innovation.',l3_guidance:'Leveraging domain insights and customer feedback, the team owns responsibility to identify and prioritize new features for the product.',sort_order:12},
  {pillar:'Customer Satisfaction',activity:'Deliver Fully Functional Product',required_level:3,l1_guidance:'The team is limited to delivering to the specification provided by the product leadership team.',l2_guidance:'The team is responsible for ensuring the implemented features meet end-user needs and achieve the desired business benefits.',l3_guidance:'The team delivers product\'s long-term vision through iterative releases. The team will go beyond software to deliver tools like manuals and user-training.',sort_order:13},
  {pillar:'Customer Satisfaction',activity:'Rigour of QA Process',required_level:2,l1_guidance:'The team will largely focus on functional testing and regression cycles — as mandated by the QA strategy drafted by the parent organization.',l2_guidance:'The team develops its QA strategy and ensures a high-quality product across all aspects, including usability, operational stability, and performance.',l3_guidance:'The team identifies product shortcomings to define and remediate technical and feature debt, ensuring ongoing market and customer relevance.',sort_order:14},
  {pillar:'High Performance Talent',activity:'Inclusive & Growth Focused Work Culture',required_level:2,l1_guidance:'The growth path will focus on deepening technical mastery, process efficiency, and team leadership roles within product execution, support, and professional services.',l2_guidance:'Team members are provided opportunity to grow into world-class SMEs, Solution Architects, and senior technical roles with direct impact on system stability and TCO.',l3_guidance:'Growth focuses on business acumen, external thought leadership, and senior strategic leadership (VP/CXO) paths, tied directly to product success and market expansion.',sort_order:15},
  {pillar:'High Performance Talent',activity:'Benefits beyond Monetary Compensation',required_level:3,l1_guidance:'Investments are made so that the team members can constantly improve their technical skill, engineering process, and project stability.',l2_guidance:'The team members are provided learning opportunities in advanced systems design, domain depth, and consultative architecture. Benefits include specialized conferences.',l3_guidance:'The team receives benefits tied to business performance (e.g., profit-sharing, equity), executive coaching, and high visibility through customer interaction.',sort_order:16},
  {pillar:'High Performance Talent',activity:'Empowering Engineering Team Members',required_level:2,l1_guidance:'Focus on process transparency and communication integration into the daily routine. Feedback on tooling, process quality, and documentation is acted upon.',l2_guidance:'The team is granted architectural and design ownership and responsibility for defining technical requirements based on inputs from business leadership.',l3_guidance:'The team is included in product strategy, P&L discussions, and go-to-market decisions, apart from representing the company in industry forums.',sort_order:17},
];

export const LEADERSHIP_SKILLS = [
  {skill_category:'Technology & Domain',skill_name:'Software Development',is_mandatory:true,detailed_skills:'Full-stack proficiency, Performance tuning, Scalability patterns, DevOps/CI/CD pipelines, Cloud infrastructure (e.g., AWS/GCP)'},
  {skill_category:'Technology & Domain',skill_name:'Design Skill',is_mandatory:true,detailed_skills:'System Architecture, Microservices, API design (REST/GraphQL), Data modeling (SQL/NoSQL), Event-driven systems'},
  {skill_category:'Technology & Domain',skill_name:'Solution Architecture',is_mandatory:true,detailed_skills:'Cross-system integration, Security best practices, Resilience engineering, Observability setup (metrics, logging, tracing)'},
  {skill_category:'Technology & Domain',skill_name:'Ecosystem Health',is_mandatory:true,detailed_skills:'Dependency management, Tech stack auditing, Open-source software (OSS) licensing compliance, Security patching process'},
  {skill_category:'Technology & Domain',skill_name:'Product Operation',is_mandatory:true,detailed_skills:'On-call management, Incident response (P1/P2), Root Cause Analysis (RCA), Service Level Objectives (SLOs) definition'},
  {skill_category:'Technology & Domain',skill_name:'Experience with Domain',is_mandatory:true,detailed_skills:'Specific industry knowledge (e.g., FinTech, Logistics, Healthcare regulatory frameworks), Understanding user workflows'},
  {skill_category:'Technology & Domain',skill_name:'Security Governance',is_mandatory:true,detailed_skills:'Threat modeling, Defining security policies, Managing secrets, Implementing encryption standards, Vulnerability management'},
  {skill_category:'Technology & Domain',skill_name:'Regulatory Compliance',is_mandatory:true,detailed_skills:'GDPR, HIPAA, PCI-DSS compliance, Data retention policies, Implementing Privacy by Design, Audit response'},
  {skill_category:'Technology & Domain',skill_name:'Thought Leadership',is_mandatory:false,detailed_skills:'Presenting at industry conferences, Publishing white papers/blogs, Patent disclosures, Contributing to OSS'},
  {skill_category:'Project Execution',skill_name:'Product LifeCycle',is_mandatory:true,detailed_skills:'Idea inception to EOL planning, Technical debt management, Feature-toggle strategies, Release governance and rollback planning'},
  {skill_category:'Project Execution',skill_name:'Prioritize Backlog',is_mandatory:true,detailed_skills:'MoSCoW, RICE/WSJF scoring, Balancing feature work vs. technical debt vs. bug fixes, Capacity planning'},
  {skill_category:'Project Execution',skill_name:'Process Improvement',is_mandatory:true,detailed_skills:'Retrospective action tracking, Value Stream Mapping, Standardizing definitions of Done, Implementing automated quality gates'},
  {skill_category:'Project Execution',skill_name:'Estimation, Planning & Costing',is_mandatory:true,detailed_skills:'Agile methodologies (Scrum/Kanban), Story point/T-shirt sizing, OpEx/CapEx understanding, Resource allocation'},
  {skill_category:'Project Execution',skill_name:'Org Design & Structuring',is_mandatory:true,detailed_skills:'Defining team topologies, Determining optimal span of control, Managing organizational debt, Setting up remote/hybrid operating models'},
  {skill_category:'Project Execution',skill_name:'Vendor Management',is_mandatory:false,detailed_skills:'Contract negotiation, SLA monitoring, Managing external development teams/consultants, Software license renewals'},
  {skill_category:'Resourcefulness',skill_name:'Stakeholder Management',is_mandatory:true,detailed_skills:'Managing expectations across sales, marketing, finance, and peer engineering teams, Effective status communication'},
  {skill_category:'Resourcefulness',skill_name:'Customer Management',is_mandatory:true,detailed_skills:'Handling executive-level customer communication, Participating in pre-sales technical deep dives, Translating customer feedback'},
  {skill_category:'Resourcefulness',skill_name:'Escalation Handling',is_mandatory:true,detailed_skills:'Defining clear escalation paths, Making high-pressure decisions during crises, Post-mortem communication'},
  {skill_category:'Resourcefulness',skill_name:'Risk Management',is_mandatory:true,detailed_skills:'Identifying technical risks (dependency deprecation, security vulnerabilities, single points of failure) and mitigation planning'},
  {skill_category:'Resourcefulness',skill_name:'Industry Forum Representation',is_mandatory:false,detailed_skills:'Leading open-source projects, Sitting on standards committees, Networking with peer leaders (e.g., CTO forums)'},
  {skill_category:'Resourcefulness',skill_name:'Knowledge Sharing & Mentoring',is_mandatory:true,detailed_skills:'Establishing internal tech talks, Formal mentorship programs, Developing internal technical career ladders, Code review standards'},
  {skill_category:'Resourcefulness',skill_name:'Communication & Influence',is_mandatory:true,detailed_skills:'Technical presentation skills (to executive level), Cross-cultural communication, Active listening, Managing conflict resolution'},
  {skill_category:'Business Maturity',skill_name:'ROI from Investment in Engineering Effort',is_mandatory:true,detailed_skills:'Developing metrics to track engineering efficiency, Cost-benefit analysis for new technology adoption, Measuring customer impact'},
  {skill_category:'Business Maturity',skill_name:'Capitalize Team\'s Knowledge & Experience',is_mandatory:true,detailed_skills:'Developing internal documentation/wikis, Creating code sharing/review standards, Institutionalizing best practices into playbooks'},
  {skill_category:'Business Maturity',skill_name:'Intellectual Property (IP) Strategy',is_mandatory:false,detailed_skills:'Patent disclosure process, Protecting trade secrets, Freedom-to-Operate analysis, Competitive technical analysis'},
  {skill_category:'Business Maturity',skill_name:'Cultural Stewardship',is_mandatory:true,detailed_skills:'Fostering psychological safety, Defining core team values, Promoting a blameless culture, Driving DEI initiatives'},
  {skill_category:'Business Maturity',skill_name:'Strategic Finance',is_mandatory:true,detailed_skills:'Managing annual OpEx/CapEx budgets, Cloud cost management (FinOps), Forecasting engineering resource needs, Negotiating major contracts'},
  {skill_category:'Business Maturity',skill_name:'M&A Due Diligence',is_mandatory:false,detailed_skills:'Technical assessment of target companies, Integration/migration planning, Post-merger technology rationalization'},
  {skill_category:'Collaborative',skill_name:'Participate in Roadmap Planning',is_mandatory:true,detailed_skills:'Translating technical capabilities/limitations into product features, Influencing product strategy with technology trends'},
  {skill_category:'Collaborative',skill_name:'Presales Effort',is_mandatory:false,detailed_skills:'Providing technical validation for sales pitches, Drafting complex Statements of Work (SOWs), Technical solutioning for large clients'},
  {skill_category:'Collaborative',skill_name:'Talent Management & Development',is_mandatory:true,detailed_skills:'Hiring/Interviewing, Performance reviews, Career coaching, Succession planning, Defining job leveling'},
  {skill_category:'Collaborative',skill_name:'Cross-Functional Alignment',is_mandatory:true,detailed_skills:'Defining Service Level Agreements (SLAs) with Product/Operations, Negotiating resource dependencies, Facilitating joint planning'},
  {skill_category:'Collaborative',skill_name:'Conflict Resolution & Negotiation',is_mandatory:true,detailed_skills:'Mediating disagreements between technical and product vision, Negotiating timelines, Resolving interpersonal conflict'},
];

export const KRA_TEMPLATE = [
  {role_level:'Sr Director, Engineering/ VP',pillar:'Operational Excellence',kra_name:'High System Availability',sort_order:1},
  {role_level:'Sr Director, Engineering/ VP',pillar:'Pace of Product Evolution',kra_name:'Lead Time for Changes (Org-wide)',sort_order:2},
  {role_level:'Sr Director, Engineering/ VP',pillar:'Alignment',kra_name:'Stakeholder Alignment Score (Cross-Functional)',sort_order:3},
  {role_level:'Sr Director, Engineering/ VP',pillar:'Business Results Focused',kra_name:'Business Impact of New Product Innovations',sort_order:4},
  {role_level:'Sr Director, Engineering/ VP',pillar:'Operational Excellence',kra_name:'Cost of Quality (COQ)',sort_order:5},
  {role_level:'Sr Director, Engineering/ VP',pillar:'Pace of Product Evolution',kra_name:'Cycle Time for Decision-Making',sort_order:6},
  {role_level:'Sr Director, Engineering/ VP',pillar:'Alignment',kra_name:'Alignment with Shared OKRs',sort_order:7},
  {role_level:'Sr Director, Engineering/ VP',pillar:'Business Results Focused',kra_name:'Percentage of New Features with Positive ROI',sort_order:8},
  {role_level:'Senior Manager/ Director, Engineering',pillar:'Operational Excellence',kra_name:'Mean Time to Recovery (MTTR)',sort_order:9},
  {role_level:'Senior Manager/ Director, Engineering',pillar:'Pace of Product Evolution',kra_name:'Customer Commitment Success Rate',sort_order:10},
  {role_level:'Senior Manager/ Director, Engineering',pillar:'Alignment',kra_name:'Roadmap Adherence',sort_order:11},
  {role_level:'Senior Manager/ Director, Engineering',pillar:'Business Results Focused',kra_name:'Customer Retention Impact',sort_order:12},
  {role_level:'Senior Manager/ Director, Engineering',pillar:'Operational Excellence',kra_name:'Optimal Resource Utilization (Planned vs Unplanned)',sort_order:13},
  {role_level:'Senior Manager/ Director, Engineering',pillar:'Pace of Product Evolution',kra_name:'Technical Debt Ratio (TDR)',sort_order:14},
  {role_level:'Senior Manager/ Director, Engineering',pillar:'Alignment',kra_name:'Engineering-to-Product Alignment Score',sort_order:15},
  {role_level:'Senior Manager/ Director, Engineering',pillar:'Business Results Focused',kra_name:'Cost Savings from Automation',sort_order:16},
  {role_level:'Manager / Project Lead',pillar:'Operational Excellence',kra_name:'Change Failure Rate',sort_order:17},
  {role_level:'Manager / Project Lead',pillar:'Pace of Product Evolution',kra_name:'Cycle Time for New Features (Team-Level)',sort_order:18},
  {role_level:'Manager / Project Lead',pillar:'Alignment',kra_name:'Backlog Health',sort_order:19},
  {role_level:'Manager / Project Lead',pillar:'Business Results Focused',kra_name:'Roadmap Adherence and Customer Commitment',sort_order:20},
  {role_level:'Manager / Project Lead',pillar:'Operational Excellence',kra_name:'WIP Limits Adherence',sort_order:21},
  {role_level:'Manager / Project Lead',pillar:'Pace of Product Evolution',kra_name:'Cross-Team Dependency Resolution Time',sort_order:22},
  {role_level:'Manager / Project Lead',pillar:'Alignment',kra_name:'Feature Usage vs. Business Case %',sort_order:23},
  {role_level:'Manager / Project Lead',pillar:'Business Results Focused',kra_name:'Feature Adoption Rate',sort_order:24},
  {role_level:'Developer / Senior Developer',pillar:'Operational Excellence',kra_name:'Automated Test Coverage',sort_order:25},
  {role_level:'Developer / Senior Developer',pillar:'Pace of Product Evolution',kra_name:'Pull Request (PR) Merge Time',sort_order:26},
  {role_level:'Developer / Senior Developer',pillar:'Alignment',kra_name:'Code Review Response Time',sort_order:27},
  {role_level:'Developer / Senior Developer',pillar:'Business Results Focused',kra_name:'Feature Adoption and TTV',sort_order:28},
  {role_level:'Developer / Senior Developer',pillar:'Operational Excellence',kra_name:'Defect Escape Rate (Code/Component)',sort_order:29},
  {role_level:'Developer / Senior Developer',pillar:'Pace of Product Evolution',kra_name:'Time-to-Value (TTV)',sort_order:30},
  {role_level:'Developer / Senior Developer',pillar:'Alignment',kra_name:'Code Maintainability Score',sort_order:31},
  {role_level:'Developer / Senior Developer',pillar:'Business Results Focused',kra_name:'Feature Stickiness / Health Score',sort_order:32},
];

export const MATURITY_TEMPLATE = [
  {factor_name:'Product Enhancement & Maintenance',maturity_level:3,sort_order:1},
  {factor_name:'Thought Leadership',maturity_level:3,sort_order:2},
  {factor_name:'Business Result Focused',maturity_level:2,sort_order:3},
  {factor_name:'Customer Satisfaction',maturity_level:2,sort_order:4},
  {factor_name:'High Performance Talent',maturity_level:2,sort_order:5},
];

export const TALENT_SKILLS_TEMPLATE: {section:string;category:string;skill_name:string;description:string;sort_order:number}[] = [
  // Technical Skills
  {section:'Technical Skills',category:'Design Patterns',skill_name:'SOLID Principles',description:'Single Responsibility, Open/Closed, Liskov Substitution, Interface Segregation, Dependency Inversion',sort_order:1},
  {section:'Technical Skills',category:'Design Patterns',skill_name:'Creational Patterns',description:'Factory, Abstract Factory, Builder, Singleton, Prototype',sort_order:2},
  {section:'Technical Skills',category:'Design Patterns',skill_name:'Structural Patterns',description:'Adapter, Bridge, Composite, Decorator, Facade, Proxy',sort_order:3},
  {section:'Technical Skills',category:'Design Patterns',skill_name:'Behavioral Patterns',description:'Observer, Strategy, Command, State, Template Method, Iterator',sort_order:4},
  {section:'Technical Skills',category:'Design Patterns',skill_name:'Architectural Patterns',description:'MVC, MVVM, Microservices, Event-Driven, CQRS, Hexagonal',sort_order:5},
  {section:'Technical Skills',category:'Coding & AI Tools',skill_name:'Clean Code Practices',description:'Readable, maintainable code with clear naming, small functions, and minimal complexity',sort_order:6},
  {section:'Technical Skills',category:'Coding & AI Tools',skill_name:'Code Review Expertise',description:'Ability to provide constructive, thorough code reviews focusing on design, correctness, and performance',sort_order:7},
  {section:'Technical Skills',category:'Coding & AI Tools',skill_name:'AI-Assisted Development',description:'Proficiency with AI coding tools (Copilot, ChatGPT, Claude) for code generation, refactoring, and debugging',sort_order:8},
  {section:'Technical Skills',category:'Coding & AI Tools',skill_name:'Test-Driven Development',description:'Writing tests first, red-green-refactor cycle, unit/integration/e2e testing',sort_order:9},
  {section:'Technical Skills',category:'Coding & AI Tools',skill_name:'Refactoring Skills',description:'Systematic code improvement without changing external behavior, eliminating code smells',sort_order:10},
  {section:'Technical Skills',category:'System Understanding',skill_name:'System Architecture',description:'Understanding of distributed systems, scalability patterns, and system design trade-offs',sort_order:11},
  {section:'Technical Skills',category:'System Understanding',skill_name:'Database Design',description:'Schema design, normalization, indexing strategies, query optimization (SQL and NoSQL)',sort_order:12},
  {section:'Technical Skills',category:'System Understanding',skill_name:'API Design',description:'RESTful API design, GraphQL, gRPC, versioning, authentication, rate limiting',sort_order:13},
  {section:'Technical Skills',category:'System Understanding',skill_name:'Cloud Infrastructure',description:'AWS/GCP/Azure services, IaC (Terraform/CloudFormation), containerization (Docker/K8s)',sort_order:14},
  {section:'Technical Skills',category:'System Understanding',skill_name:'Security Fundamentals',description:'OWASP Top 10, authentication/authorization, encryption, vulnerability assessment',sort_order:15},
  {section:'Technical Skills',category:'Operational Factors',skill_name:'CI/CD Pipeline Management',description:'Build, test, deploy automation; environment management; release strategies',sort_order:16},
  {section:'Technical Skills',category:'Operational Factors',skill_name:'Monitoring & Observability',description:'Logging, metrics, tracing, alerting; tools like Datadog, Grafana, ELK',sort_order:17},
  {section:'Technical Skills',category:'Operational Factors',skill_name:'Incident Response',description:'On-call readiness, incident triage, root cause analysis, post-mortem documentation',sort_order:18},
  {section:'Technical Skills',category:'Operational Factors',skill_name:'Performance Optimization',description:'Profiling, load testing, caching strategies, database tuning, CDN optimization',sort_order:19},
  {section:'Technical Skills',category:'Sizing & Deployment',skill_name:'Capacity Planning',description:'Resource estimation, load forecasting, auto-scaling configuration',sort_order:20},
  {section:'Technical Skills',category:'Sizing & Deployment',skill_name:'Deployment Strategies',description:'Blue-green, canary, rolling deployments, feature flags, rollback procedures',sort_order:21},
  {section:'Technical Skills',category:'Sizing & Deployment',skill_name:'Cost Optimization',description:'Cloud cost management, right-sizing, reserved instances, spot instances',sort_order:22},
  // Product Mindset
  {section:'Product Mindset',category:'Attitude',skill_name:'Ownership Mentality',description:'Takes end-to-end responsibility for features from ideation to production monitoring',sort_order:23},
  {section:'Product Mindset',category:'Attitude',skill_name:'Curiosity & Learning',description:'Proactively explores new technologies, reads documentation, experiments with PoCs',sort_order:24},
  {section:'Product Mindset',category:'Attitude',skill_name:'Bias for Action',description:'Makes progress without waiting for perfect information; ships iteratively',sort_order:25},
  {section:'Product Mindset',category:'Attitude',skill_name:'Resilience',description:'Handles setbacks, production incidents, and changing requirements with composure',sort_order:26},
  {section:'Product Mindset',category:'Collaboration',skill_name:'Cross-Team Communication',description:'Effectively communicates with product, design, QA, and business stakeholders',sort_order:27},
  {section:'Product Mindset',category:'Collaboration',skill_name:'Pair Programming',description:'Productive in pair/mob programming sessions, knowledge sharing through collaboration',sort_order:28},
  {section:'Product Mindset',category:'Collaboration',skill_name:'Mentoring Ability',description:'Guides junior team members, provides constructive feedback, fosters growth',sort_order:29},
  {section:'Product Mindset',category:'Collaboration',skill_name:'Conflict Resolution',description:'Addresses disagreements constructively, focuses on solutions over blame',sort_order:30},
  {section:'Product Mindset',category:'Knowledge',skill_name:'Domain Expertise',description:'Deep understanding of the business domain, user workflows, and industry regulations',sort_order:31},
  {section:'Product Mindset',category:'Knowledge',skill_name:'Technical Documentation',description:'Creates clear architecture docs, ADRs, runbooks, and onboarding guides',sort_order:32},
  {section:'Product Mindset',category:'Knowledge',skill_name:'Data-Driven Decisions',description:'Uses metrics, A/B tests, and user analytics to inform technical decisions',sort_order:33},
  {section:'Product Mindset',category:'Product Lifecycle Engagement',skill_name:'Requirements Analysis',description:'Translates business requirements into technical specifications and user stories',sort_order:34},
  {section:'Product Mindset',category:'Product Lifecycle Engagement',skill_name:'Release Planning',description:'Participates in sprint planning, story sizing, and release coordination',sort_order:35},
  {section:'Product Mindset',category:'Product Lifecycle Engagement',skill_name:'User Empathy',description:'Considers end-user experience in technical decisions, participates in user research',sort_order:36},
  {section:'Product Mindset',category:'Product Lifecycle Engagement',skill_name:'Feedback Loop Participation',description:'Acts on customer feedback, production metrics, and retrospective outcomes',sort_order:37},
  // Knowledge Management
  {section:'Knowledge Management',category:'Self-Evaluation',skill_name:'Skills Self-Assessment',description:'Regularly evaluates own technical and soft skills against career framework',sort_order:38},
  {section:'Knowledge Management',category:'Self-Evaluation',skill_name:'Goal Setting',description:'Sets SMART goals for professional development aligned with team objectives',sort_order:39},
  {section:'Knowledge Management',category:'Self-Evaluation',skill_name:'Strengths Identification',description:'Identifies and leverages personal strengths for team benefit',sort_order:40},
  {section:'Knowledge Management',category:'Self-Evaluation',skill_name:'Gap Awareness',description:'Honestly identifies skill gaps and creates plans to address them',sort_order:41},
  {section:'Knowledge Management',category:'Skill Tracking',skill_name:'Learning Plan Execution',description:'Follows through on planned learning activities (courses, certifications, reading)',sort_order:42},
  {section:'Knowledge Management',category:'Skill Tracking',skill_name:'Certification Progress',description:'Pursues relevant industry certifications (AWS, GCP, Kubernetes, etc.)',sort_order:43},
  {section:'Knowledge Management',category:'Skill Tracking',skill_name:'Skill Matrix Updates',description:'Keeps team skill matrix current, identifies coverage gaps',sort_order:44},
  {section:'Knowledge Management',category:'Training & Development',skill_name:'Internal Training Contribution',description:'Conducts tech talks, workshops, or brown bag sessions for the team',sort_order:45},
  {section:'Knowledge Management',category:'Training & Development',skill_name:'External Learning',description:'Attends conferences, meetups, webinars; brings back insights to the team',sort_order:46},
  {section:'Knowledge Management',category:'Training & Development',skill_name:'Hands-On Practice',description:'Builds side projects, contributes to open source, participates in hackathons',sort_order:47},
  {section:'Knowledge Management',category:'Research & Community',skill_name:'Technology Evaluation',description:'Evaluates new tools, frameworks, and platforms for potential team adoption',sort_order:48},
  {section:'Knowledge Management',category:'Research & Community',skill_name:'Community Participation',description:'Active in developer communities, forums, or open-source projects',sort_order:49},
  {section:'Knowledge Management',category:'Research & Community',skill_name:'Knowledge Sharing Culture',description:'Contributes to team wiki, internal blog posts, or documentation repositories',sort_order:50},
  {section:'Knowledge Management',category:'Progress Review',skill_name:'Quarterly Skill Review',description:'Participates in regular skill assessment reviews with manager',sort_order:51},
  {section:'Knowledge Management',category:'Progress Review',skill_name:'Career Path Alignment',description:'Aligns skill development with career progression framework',sort_order:52},
  {section:'Knowledge Management',category:'Progress Review',skill_name:'Impact Measurement',description:'Measures how skill improvements translate to team productivity and quality',sort_order:53},
  // AI Readiness
  {section:'AI Readiness',category:'Phase 1 — Foundation',skill_name:'AI Tool Adoption',description:'Uses AI coding assistants (Copilot, ChatGPT) for everyday development tasks',sort_order:54},
  {section:'AI Readiness',category:'Phase 1 — Foundation',skill_name:'Prompt Engineering Basics',description:'Crafts effective prompts for code generation, debugging, and documentation',sort_order:55},
  {section:'AI Readiness',category:'Phase 1 — Foundation',skill_name:'AI-Generated Code Review',description:'Critically evaluates AI-generated code for correctness, security, and maintainability',sort_order:56},
  {section:'AI Readiness',category:'Phase 1 — Foundation',skill_name:'AI for Testing',description:'Uses AI to generate test cases, identify edge cases, and improve test coverage',sort_order:57},
  {section:'AI Readiness',category:'Phase 1 — Foundation',skill_name:'AI Documentation',description:'Leverages AI for generating and maintaining documentation, commit messages, PR descriptions',sort_order:58},
  {section:'AI Readiness',category:'Phase 1 — Foundation',skill_name:'AI Ethics Awareness',description:'Understands bias, privacy, and security implications of AI-generated code',sort_order:59},
  {section:'AI Readiness',category:'Phase 2 — Integration',skill_name:'AI Pipeline Integration',description:'Integrates AI into CI/CD pipelines for automated code review, security scanning',sort_order:60},
  {section:'AI Readiness',category:'Phase 2 — Integration',skill_name:'Custom AI Workflows',description:'Builds custom AI workflows for domain-specific development tasks',sort_order:61},
  {section:'AI Readiness',category:'Phase 2 — Integration',skill_name:'AI-Powered Analytics',description:'Uses AI for log analysis, anomaly detection, and predictive monitoring',sort_order:62},
  {section:'AI Readiness',category:'Phase 2 — Integration',skill_name:'ML Model Integration',description:'Integrates pre-trained ML models into applications (APIs, edge deployment)',sort_order:63},
  {section:'AI Readiness',category:'Phase 2 — Integration',skill_name:'Data Pipeline for AI',description:'Builds data pipelines to support AI/ML feature development',sort_order:64},
  {section:'AI Readiness',category:'Phase 2 — Integration',skill_name:'AI Performance Optimization',description:'Optimizes AI model inference time, resource usage, and cost',sort_order:65},
  {section:'AI Readiness',category:'Phase 3 — Leadership',skill_name:'AI Strategy Development',description:'Contributes to organizational AI adoption strategy and roadmap',sort_order:66},
  {section:'AI Readiness',category:'Phase 3 — Leadership',skill_name:'AI Product Innovation',description:'Identifies opportunities to build AI-native product features',sort_order:67},
  {section:'AI Readiness',category:'Phase 3 — Leadership',skill_name:'AI Team Enablement',description:'Trains and mentors team members on AI tools and best practices',sort_order:68},
  {section:'AI Readiness',category:'Phase 3 — Leadership',skill_name:'AI Governance',description:'Establishes guidelines for responsible AI use in development workflows',sort_order:69},
  {section:'AI Readiness',category:'Phase 3 — Leadership',skill_name:'AI ROI Measurement',description:'Measures and reports on productivity gains from AI tool adoption',sort_order:70},
];

export const SKILLSET_CONTEXT_TEMPLATE: {field_name:string;field_value:string;field_group:string;sort_order:number}[] = [
  {field_name:'Product Name',field_value:'',field_group:'basics',sort_order:1},
  {field_name:'Industry / Domain',field_value:'',field_group:'basics',sort_order:2},
  {field_name:'Product Stage',field_value:'Growth',field_group:'basics',sort_order:3},
  {field_name:'Team Size',field_value:'',field_group:'basics',sort_order:4},
  {field_name:'Primary Tech Stack',field_value:'',field_group:'technical',sort_order:5},
  {field_name:'Deployment Model',field_value:'Cloud',field_group:'technical',sort_order:6},
  {field_name:'Architecture Style',field_value:'Microservices',field_group:'technical',sort_order:7},
  {field_name:'Compliance Requirements',field_value:'',field_group:'technical',sort_order:8},
  {field_name:'AI/ML Integration Level',field_value:'Phase 1',field_group:'technical',sort_order:9},
  {field_name:'Customer Base',field_value:'',field_group:'business',sort_order:10},
  {field_name:'Release Cadence',field_value:'Bi-weekly',field_group:'business',sort_order:11},
  {field_name:'Offshore Percentage',field_value:'',field_group:'business',sort_order:12},
];

export const SKILLSET_ITEMS_TEMPLATE: {section:string;category:string;item_name:string;description:string;importance:string;required_level:string;sort_order:number}[] = [
  // Core Engineering Skills
  {section:'Core Engineering',category:'Languages & Frameworks',item_name:'Primary Language Proficiency',description:'Deep expertise in the primary programming language used by the team',importance:'Critical',required_level:'Advanced',sort_order:1},
  {section:'Core Engineering',category:'Languages & Frameworks',item_name:'Framework Mastery',description:'Proficiency in primary web/mobile/backend frameworks (React, Spring, Django, etc.)',importance:'Critical',required_level:'Advanced',sort_order:2},
  {section:'Core Engineering',category:'Languages & Frameworks',item_name:'Secondary Language',description:'Working knowledge of a secondary language for specific use cases',importance:'Important',required_level:'Intermediate',sort_order:3},
  {section:'Core Engineering',category:'Data & Storage',item_name:'Relational Databases',description:'SQL, schema design, query optimization, migrations, replication',importance:'Critical',required_level:'Advanced',sort_order:4},
  {section:'Core Engineering',category:'Data & Storage',item_name:'NoSQL Databases',description:'Document stores, key-value stores, graph databases — when and how to use each',importance:'Important',required_level:'Intermediate',sort_order:5},
  {section:'Core Engineering',category:'Data & Storage',item_name:'Caching Strategies',description:'Redis, Memcached, CDN caching, application-level caching patterns',importance:'Important',required_level:'Intermediate',sort_order:6},
  {section:'Core Engineering',category:'Infrastructure',item_name:'Cloud Platform',description:'Core cloud services (compute, storage, networking, IAM) on primary cloud provider',importance:'Critical',required_level:'Advanced',sort_order:7},
  {section:'Core Engineering',category:'Infrastructure',item_name:'Containerization',description:'Docker, Kubernetes, container orchestration, service mesh',importance:'Critical',required_level:'Intermediate',sort_order:8},
  {section:'Core Engineering',category:'Infrastructure',item_name:'CI/CD',description:'Pipeline design, automated testing, deployment automation, environment management',importance:'Critical',required_level:'Advanced',sort_order:9},
  // Architecture & Design
  {section:'Architecture & Design',category:'System Design',item_name:'Distributed Systems',description:'CAP theorem, consensus, eventual consistency, partitioning strategies',importance:'Critical',required_level:'Advanced',sort_order:10},
  {section:'Architecture & Design',category:'System Design',item_name:'API Design & Integration',description:'REST, GraphQL, gRPC, API gateways, versioning, backward compatibility',importance:'Critical',required_level:'Advanced',sort_order:11},
  {section:'Architecture & Design',category:'System Design',item_name:'Event-Driven Architecture',description:'Message queues, event sourcing, CQRS, pub/sub patterns',importance:'Important',required_level:'Intermediate',sort_order:12},
  {section:'Architecture & Design',category:'Security',item_name:'Application Security',description:'OWASP Top 10, secure coding practices, authentication/authorization patterns',importance:'Critical',required_level:'Advanced',sort_order:13},
  {section:'Architecture & Design',category:'Security',item_name:'Data Protection',description:'Encryption at rest/in transit, PII handling, data classification, access controls',importance:'Critical',required_level:'Intermediate',sort_order:14},
  {section:'Architecture & Design',category:'Reliability',item_name:'High Availability Design',description:'Redundancy, failover, load balancing, disaster recovery planning',importance:'Critical',required_level:'Intermediate',sort_order:15},
  {section:'Architecture & Design',category:'Reliability',item_name:'Performance Engineering',description:'Load testing, profiling, optimization techniques, SLO/SLA definition',importance:'Important',required_level:'Intermediate',sort_order:16},
  // Quality & Testing
  {section:'Quality & Testing',category:'Testing Strategy',item_name:'Unit Testing',description:'Test isolation, mocking, assertion patterns, coverage targets',importance:'Critical',required_level:'Advanced',sort_order:17},
  {section:'Quality & Testing',category:'Testing Strategy',item_name:'Integration Testing',description:'API testing, database testing, contract testing between services',importance:'Critical',required_level:'Intermediate',sort_order:18},
  {section:'Quality & Testing',category:'Testing Strategy',item_name:'E2E & Performance Testing',description:'End-to-end test automation, load testing, stress testing, chaos engineering',importance:'Important',required_level:'Intermediate',sort_order:19},
  {section:'Quality & Testing',category:'Quality Practices',item_name:'Code Review Standards',description:'Review checklists, constructive feedback, architectural review process',importance:'Critical',required_level:'Advanced',sort_order:20},
  {section:'Quality & Testing',category:'Quality Practices',item_name:'Technical Debt Management',description:'Identification, tracking, prioritization, and systematic reduction of tech debt',importance:'Important',required_level:'Intermediate',sort_order:21},
  // Team & Process
  {section:'Team & Process',category:'Agile Practices',item_name:'Sprint Execution',description:'Story writing, estimation, sprint planning, retrospectives, velocity tracking',importance:'Critical',required_level:'Advanced',sort_order:22},
  {section:'Team & Process',category:'Agile Practices',item_name:'Cross-Functional Collaboration',description:'Working effectively with product, design, QA, and DevOps teams',importance:'Critical',required_level:'Advanced',sort_order:23},
  {section:'Team & Process',category:'Talent Development',item_name:'Hiring & Interviewing',description:'Technical interview design, candidate evaluation, hiring bar calibration',importance:'Important',required_level:'Intermediate',sort_order:24},
  {section:'Team & Process',category:'Talent Development',item_name:'Onboarding & Mentoring',description:'New hire ramp-up programs, buddy systems, structured mentoring',importance:'Important',required_level:'Intermediate',sort_order:25},
  {section:'Team & Process',category:'Talent Development',item_name:'Career Framework',description:'Engineering ladder definition, promotion criteria, growth planning',importance:'Important',required_level:'Intermediate',sort_order:26},
  // AI & Innovation
  {section:'AI & Innovation',category:'AI Adoption',item_name:'AI-Assisted Development',description:'Team-wide adoption of AI coding tools with productivity measurement',importance:'Critical',required_level:'Intermediate',sort_order:27},
  {section:'AI & Innovation',category:'AI Adoption',item_name:'AI/ML Feature Development',description:'Ability to build and integrate AI-powered product features',importance:'Important',required_level:'Basic',sort_order:28},
  {section:'AI & Innovation',category:'Innovation',item_name:'Technology Radar',description:'Systematic evaluation and adoption of emerging technologies',importance:'Important',required_level:'Intermediate',sort_order:29},
  {section:'AI & Innovation',category:'Innovation',item_name:'Experimentation Culture',description:'PoC development, A/B testing, innovation sprints, hackathons',importance:'Important',required_level:'Intermediate',sort_order:30},
];
