import { Pool } from 'pg';
let _pool: Pool | null = null;
export function getPool(): Pool {
  if (!_pool) _pool = new Pool({ connectionString: process.env.DATABASE_URL, ssl: process.env.DATABASE_SSL === 'true' ? { rejectUnauthorized: false } : undefined, max: 10, idleTimeoutMillis: 30000 });
  return _pool;
}
export async function query<T = Record<string, unknown>>(sql: string, values?: unknown[]): Promise<T[]> {
  await ensureInit(); const result = await getPool().query(sql, values); return result.rows as T[];
}
export async function queryOne<T = Record<string, unknown>>(sql: string, values?: unknown[]): Promise<T | undefined> {
  const rows = await query<T>(sql, values); return rows[0];
}
export async function execute(sql: string, values?: unknown[]): Promise<number> {
  await ensureInit(); const result = await getPool().query(sql, values); return result.rowCount ?? 0;
}
let _initialized = false;
async function ensureInit() { if (_initialized) return; _initialized = true; await initSchema(); }

export async function initSchema() {
  const pool = getPool();
  await pool.query(`
    CREATE TABLE IF NOT EXISTS users (id SERIAL PRIMARY KEY, name TEXT NOT NULL, email TEXT NOT NULL UNIQUE, company TEXT, role TEXT, industry TEXT, team_size TEXT, linkedin TEXT, bio TEXT, status TEXT NOT NULL DEFAULT 'active', is_admin BOOLEAN NOT NULL DEFAULT FALSE, joined_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), last_login TIMESTAMPTZ);
    CREATE TABLE IF NOT EXISTS otp_codes (id SERIAL PRIMARY KEY, email TEXT NOT NULL, code TEXT NOT NULL, purpose TEXT NOT NULL DEFAULT 'login', expires_at TIMESTAMPTZ NOT NULL, used BOOLEAN NOT NULL DEFAULT FALSE, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
    CREATE TABLE IF NOT EXISTS assessments (id SERIAL PRIMARY KEY, user_id INTEGER NOT NULL REFERENCES users(id), team_name TEXT NOT NULL DEFAULT 'My Team', industry TEXT, assessment_date DATE NOT NULL DEFAULT CURRENT_DATE, notes TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
    CREATE TABLE IF NOT EXISTS assessment_collaborators (id SERIAL PRIMARY KEY, assessment_id INTEGER NOT NULL REFERENCES assessments(id) ON DELETE CASCADE, user_id INTEGER NOT NULL REFERENCES users(id), invited_by INTEGER NOT NULL REFERENCES users(id), invited_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), UNIQUE(assessment_id, user_id));
    CREATE TABLE IF NOT EXISTS assessment_emb (id SERIAL PRIMARY KEY, assessment_id INTEGER NOT NULL REFERENCES assessments(id) ON DELETE CASCADE, pivot_num INTEGER NOT NULL, pivot_name TEXT NOT NULL, capability TEXT NOT NULL, l1_criteria TEXT, l2_criteria TEXT, l3_criteria TEXT, current_level TEXT DEFAULT 'L1', score_icon TEXT DEFAULT 'diamond', evidence TEXT, gap_notes TEXT, sort_order INTEGER DEFAULT 0);
    CREATE TABLE IF NOT EXISTS assessment_business_drivers (id SERIAL PRIMARY KEY, assessment_id INTEGER NOT NULL REFERENCES assessments(id) ON DELETE CASCADE, category TEXT NOT NULL DEFAULT 'Engineering Cost', driver_name TEXT NOT NULL DEFAULT 'New Driver', description TEXT, is_mandatory BOOLEAN NOT NULL DEFAULT FALSE, considerations TEXT, notes TEXT, sort_order INTEGER DEFAULT 0);
    CREATE TABLE IF NOT EXISTS assessment_benchmarks (id SERIAL PRIMARY KEY, assessment_id INTEGER NOT NULL REFERENCES assessments(id) ON DELETE CASCADE, pillar TEXT NOT NULL, kpi_name TEXT NOT NULL, unit TEXT, target_value TEXT, current_value TEXT, status TEXT NOT NULL DEFAULT 'pending', notes TEXT, sort_order INTEGER DEFAULT 0, weight DECIMAL DEFAULT 0, definition TEXT, sub_category TEXT);
    CREATE TABLE IF NOT EXISTS assessment_scope (id SERIAL PRIMARY KEY, assessment_id INTEGER NOT NULL REFERENCES assessments(id) ON DELETE CASCADE, pillar TEXT NOT NULL, activity TEXT NOT NULL DEFAULT 'New Activity', required_level INTEGER NOT NULL DEFAULT 1, current_level INTEGER NOT NULL DEFAULT 1, gap INTEGER NOT NULL DEFAULT 0, notes TEXT, sort_order INTEGER DEFAULT 0, l1_guidance TEXT, l2_guidance TEXT, l3_guidance TEXT);
    CREATE TABLE IF NOT EXISTS assessment_kra (id SERIAL PRIMARY KEY, assessment_id INTEGER NOT NULL REFERENCES assessments(id) ON DELETE CASCADE, role_level TEXT NOT NULL DEFAULT 'Manager', person_name TEXT, kra_name TEXT NOT NULL DEFAULT 'New KRA', description TEXT, target TEXT, current TEXT, status TEXT NOT NULL DEFAULT 'not-started', notes TEXT, sort_order INTEGER DEFAULT 0, pillar TEXT);
    CREATE TABLE IF NOT EXISTS assessment_leadership (id SERIAL PRIMARY KEY, assessment_id INTEGER NOT NULL REFERENCES assessments(id) ON DELETE CASCADE, leader_name TEXT NOT NULL DEFAULT 'Leader', leader_role TEXT, skill_name TEXT NOT NULL, is_mandatory BOOLEAN NOT NULL DEFAULT FALSE, score INTEGER NOT NULL DEFAULT 0, notes TEXT, sort_order INTEGER DEFAULT 0, skill_category TEXT, detailed_skills TEXT);
    CREATE TABLE IF NOT EXISTS assessment_maturity_levels (id SERIAL PRIMARY KEY, assessment_id INTEGER NOT NULL REFERENCES assessments(id) ON DELETE CASCADE, factor_name TEXT NOT NULL, maturity_level INTEGER NOT NULL DEFAULT 1, ownership_level TEXT, skill_level TEXT, business_value TEXT, notes TEXT, sort_order INTEGER DEFAULT 0);
    CREATE TABLE IF NOT EXISTS chat_usage (id SERIAL PRIMARY KEY, user_id INTEGER NOT NULL REFERENCES users(id), message_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
    CREATE INDEX IF NOT EXISTS chat_usage_user_time ON chat_usage(user_id, message_at);
    CREATE TABLE IF NOT EXISTS blog_posts (id SERIAL PRIMARY KEY, title TEXT NOT NULL, category TEXT, excerpt TEXT, body TEXT, emoji TEXT DEFAULT '📝', read_time INTEGER DEFAULT 4, status TEXT NOT NULL DEFAULT 'draft', author_name TEXT DEFAULT 'The Pivot Model', published_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
    CREATE TABLE IF NOT EXISTS whitepapers (id SERIAL PRIMARY KEY, title TEXT NOT NULL, category TEXT, description TEXT, icon TEXT DEFAULT '📄', pages INTEGER DEFAULT 1, access TEXT NOT NULL DEFAULT 'members', file_url TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
    CREATE TABLE IF NOT EXISTS leads (id SERIAL PRIMARY KEY, name TEXT NOT NULL, email TEXT NOT NULL, company TEXT NOT NULL, role TEXT, industry TEXT, linkedin TEXT, team_size TEXT, challenges TEXT, service TEXT, status TEXT NOT NULL DEFAULT 'new', source TEXT, submitted_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
    CREATE TABLE IF NOT EXISTS settings (key TEXT PRIMARY KEY, value TEXT, updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
  `);
  // Migrations for existing databases
  const migrations = [
    `ALTER TABLE assessment_business_drivers ADD COLUMN IF NOT EXISTS is_mandatory BOOLEAN NOT NULL DEFAULT FALSE`,
    `ALTER TABLE assessment_business_drivers ADD COLUMN IF NOT EXISTS considerations TEXT`,
    `ALTER TABLE assessment_benchmarks ADD COLUMN IF NOT EXISTS weight DECIMAL DEFAULT 0`,
    `ALTER TABLE assessment_benchmarks ADD COLUMN IF NOT EXISTS definition TEXT`,
    `ALTER TABLE assessment_benchmarks ADD COLUMN IF NOT EXISTS sub_category TEXT`,
    `ALTER TABLE assessment_scope ADD COLUMN IF NOT EXISTS l1_guidance TEXT`,
    `ALTER TABLE assessment_scope ADD COLUMN IF NOT EXISTS l2_guidance TEXT`,
    `ALTER TABLE assessment_scope ADD COLUMN IF NOT EXISTS l3_guidance TEXT`,
    `ALTER TABLE assessment_kra ADD COLUMN IF NOT EXISTS pillar TEXT`,
    `ALTER TABLE assessment_leadership ADD COLUMN IF NOT EXISTS skill_category TEXT`,
    `ALTER TABLE assessment_leadership ADD COLUMN IF NOT EXISTS detailed_skills TEXT`,
  ];
  for (const m of migrations) { try { await pool.query(m); } catch {} }
  await seedDefaults(pool);
}

async function seedDefaults(pool: Pool) {
  const { rows: ar } = await pool.query("SELECT id FROM users WHERE email = 'pivotrics@gmail.com'");
  if (ar.length === 0) await pool.query("INSERT INTO users (name, email, status, is_admin) VALUES ('Admin', 'pivotrics@gmail.com', 'active', TRUE)");
  const { rows: sr } = await pool.query('SELECT COUNT(*) AS c FROM settings');
  if (parseInt(sr[0].c) === 0) await pool.query(`INSERT INTO settings (key, value) VALUES ('site_name','The Pivot Model'),('chat_enabled','false'),('chat_api_key',''),('chat_system_prompt','You are a helpful assistant for The Pivot Model book. Answer questions about engineering team maturity, offshore operations, and the EMB framework only.'),('chat_limit_day','20'),('chat_limit_week','80'),('chat_limit_month','200'),('otp_enabled','true')`);
  const { rows: pr } = await pool.query('SELECT COUNT(*) AS c FROM blog_posts');
  if (parseInt(pr[0].c) === 0) {
    await pool.query(`INSERT INTO blog_posts (title,category,excerpt,emoji,read_time,status,published_at) VALUES ('Why Most Offshore Engineering Teams Stay at L1','Engineering Maturity','The L1 trap is real — and it''s not the offshore team''s fault.','🔒',4,'published',NOW()-INTERVAL '7 days'),('The AI Readiness Paradox for Offshore Teams','AI & Developer Tools','AI amplifies existing engineering maturity — it doesn''t create it.','🤖',5,'published',NOW()-INTERVAL '14 days'),('Captive vs Third-Party Offshore: The Decision Framework','Offshore Operations','Neither model is superior. The right choice depends on five factors.','🏗️',6,'published',NOW()-INTERVAL '21 days')`);
    await pool.query(`INSERT INTO whitepapers (title,category,description,icon,pages,access) VALUES ('The EMB Framework','Framework Reference','Complete Engineering Maturity Benchmark reference with all criteria and scoring rubrics.','📊',24,'members'),('AI Readiness for Offshore Teams','AI & Developer Tools','Navigating Phases 1, 2 and 3 of AI adoption in offshore engineering centres.','🤖',18,'members'),('The Offshore Team Scorecard','Tools & Templates','Quick self-assessment tool — score your team in under 20 minutes.','✅',8,'public')`);
  }
}

export async function getSetting(key: string): Promise<string | null> {
  const row = await queryOne<{ value: string }>('SELECT value FROM settings WHERE key = $1', [key]);
  return row?.value ?? null;
}
export async function setSetting(key: string, value: string): Promise<void> {
  await execute(`INSERT INTO settings (key,value,updated_at) VALUES ($1,$2,NOW()) ON CONFLICT (key) DO UPDATE SET value=EXCLUDED.value,updated_at=NOW()`, [key, value]);
}

export const EMB_TEMPLATE = [
  { pivot_num:1,pivot_name:'Operational Excellence',capability:'Code Quality & Review',l1_criteria:'Code is functional; basic reviews happen ad-hoc',l2_criteria:'Consistent PR reviews with quality gates; lint & static analysis in CI',l3_criteria:'Ownership culture; engineers proactively raise quality standards',sort_order:1},
  { pivot_num:1,pivot_name:'Operational Excellence',capability:'Testing Discipline',l1_criteria:'Manual testing primarily; unit tests sparse',l2_criteria:'Unit & integration tests standard; coverage tracked',l3_criteria:'TDD mindset; test coverage > 80%; performance & regression suites',sort_order:2},
  { pivot_num:1,pivot_name:'Operational Excellence',capability:'CI/CD & Build Pipeline',l1_criteria:'Manual or semi-automated deployments',l2_criteria:'Automated CI/CD; environments properly separated',l3_criteria:'Zero-downtime deploys; feature flags; automated rollback',sort_order:3},
  { pivot_num:1,pivot_name:'Operational Excellence',capability:'Incident & On-Call Management',l1_criteria:'Reactive; escalation dependent on single individuals',l2_criteria:'On-call rotation; post-mortems conducted',l3_criteria:'Blameless culture; SLOs/SLAs defined and tracked; proactive alerting',sort_order:4},
  { pivot_num:1,pivot_name:'Operational Excellence',capability:'Documentation Standards',l1_criteria:'Documentation sparse or outdated',l2_criteria:'APIs and systems documented; runbooks maintained',l3_criteria:'Living documentation culture; architecture decisions recorded',sort_order:5},
  { pivot_num:2,pivot_name:'Pace of Product Evolution',capability:'Sprint Velocity & Predictability',l1_criteria:'Sprints frequently miss targets; estimation inconsistent',l2_criteria:'Stable velocity; 80%+ sprint commitments met',l3_criteria:'Predictable delivery with clear capacity planning',sort_order:6},
  { pivot_num:2,pivot_name:'Pace of Product Evolution',capability:'Technical Debt Management',l1_criteria:'Debt accumulates unchecked; no tracking',l2_criteria:'Debt tracked and allocated budget in sprints',l3_criteria:'Proactive refactoring; debt ratio declining; architectural clarity',sort_order:7},
  { pivot_num:2,pivot_name:'Pace of Product Evolution',capability:'Feature Delivery Speed',l1_criteria:'High cycle time; long lead times',l2_criteria:'Reasonable lead times; cycle time tracked and improving',l3_criteria:'Lean flow; small batch sizes; continuous delivery',sort_order:8},
  { pivot_num:2,pivot_name:'Pace of Product Evolution',capability:'Innovation & Continuous Improvement',l1_criteria:'Reactive; no time for improvement',l2_criteria:'Regular retrospectives; process improvements implemented',l3_criteria:'Engineers drive innovation; experimentation encouraged',sort_order:9},
  { pivot_num:3,pivot_name:'Collaboration & Alignment',capability:'Stakeholder Communication',l1_criteria:'Communication reactive; status updates only when asked',l2_criteria:'Regular structured updates; blockers surfaced proactively',l3_criteria:'Engineers communicate business context; trusted partners to onshore',sort_order:10},
  { pivot_num:3,pivot_name:'Collaboration & Alignment',capability:'Cross-Team Collaboration',l1_criteria:'Siloed; minimal coordination outside own team',l2_criteria:'Regular cross-team sync; dependencies managed',l3_criteria:'Collaborative problem-solving; shared ownership across teams',sort_order:11},
  { pivot_num:3,pivot_name:'Collaboration & Alignment',capability:'Cultural Integration',l1_criteria:'Cultural gap significant; us-vs-them mentality',l2_criteria:'Cultural awareness growing; some integration initiatives',l3_criteria:'Genuinely integrated culture; offshore seen as equal partner',sort_order:12},
  { pivot_num:3,pivot_name:'Collaboration & Alignment',capability:'Knowledge Sharing',l1_criteria:'Knowledge siloed in individuals; no documentation culture',l2_criteria:'Regular knowledge sharing sessions; wikis maintained',l3_criteria:'Continuous learning culture; internal talks; mentoring programs',sort_order:13},
  { pivot_num:4,pivot_name:'Business Results',capability:'Business Impact Awareness',l1_criteria:'Engineers unaware of business metrics',l2_criteria:'Team understands product KPIs; can connect work to outcomes',l3_criteria:'Engineers drive business conversations; suggest product improvements',sort_order:14},
  { pivot_num:4,pivot_name:'Business Results',capability:'KRA Achievement',l1_criteria:'KRAs unclear or unmeasured',l2_criteria:'KRAs defined per role; tracked quarterly',l3_criteria:'KRAs tied to business OKRs; self-managed accountability',sort_order:15},
  { pivot_num:4,pivot_name:'Business Results',capability:'Customer Orientation',l1_criteria:'No direct customer interaction or feedback loop',l2_criteria:'Engineers exposed to customer feedback; user stories understood',l3_criteria:'Engineers participate in customer calls; empathy drives design',sort_order:16},
  { pivot_num:4,pivot_name:'Business Results',capability:'Strategic Contribution',l1_criteria:'Offshore purely execution; no input to strategy',l2_criteria:'Offshore contributes to technical roadmap',l3_criteria:'Offshore drives product innovation; strategic thought partner',sort_order:17},
  { pivot_num:5,pivot_name:'People & Talent',capability:'Hiring Quality',l1_criteria:'Reactive hiring; skills assessed informally',l2_criteria:'Structured interviews; defined scorecards; bar-raiser in process',l3_criteria:'Elite talent pipeline; offshore competes globally for top talent',sort_order:18},
  { pivot_num:5,pivot_name:'People & Talent',capability:'Retention & Growth',l1_criteria:'High attrition; no career framework',l2_criteria:'Career paths defined; mentoring present; attrition tracked',l3_criteria:'Low attrition; strong internal mobility; engineers actively growing',sort_order:19},
  { pivot_num:5,pivot_name:'People & Talent',capability:'Leadership Pipeline',l1_criteria:'No defined senior / staff / principal track offshore',l2_criteria:'Senior engineers visible; team leads emerging',l3_criteria:'Strong offshore leadership; directors and VPs developed internally',sort_order:20},
  { pivot_num:5,pivot_name:'People & Talent',capability:'AI & Tool Adoption',l1_criteria:'No AI tooling; awareness low',l2_criteria:'Copilot / AI tools adopted; productivity improving',l3_criteria:'AI-native workflows; engineers amplified 2x+ by tooling',sort_order:21},
];

export const DRIVER_TEMPLATE = [
  {category:'Engineering Cost',driver_name:'Investment Decision',is_mandatory:true,considerations:'* Data driven decision making (portfolio management)\n* Prioritize features & backlogs\n* Track ROI on investment in engineering activities',sort_order:1},
  {category:'Engineering Cost',driver_name:'Cost Advantage of Offshore Operation',is_mandatory:true,considerations:'* Target Operational Cost\n* Target for Total Cost of Product Ownership\n* Higher value-per-dollar / ROI',sort_order:2},
  {category:'Engineering Cost',driver_name:'Team Size / Headcount',is_mandatory:true,considerations:'* Source of budget (R&D Budget vs Customer Funded)\n* Headcount approval process\n* Goal Alignment & HC Forecasting\n* Talent & Skill Management\n* Offshore Factors',sort_order:3},
  {category:'Scale of Engineering Operations',driver_name:'Reason for Increasing Team Size',is_mandatory:false,considerations:'* New skills required to address architectural and technical complexities\n* Increase in System size & scope\n* Technical Liabilities',sort_order:4},
  {category:'Scale of Engineering Operations',driver_name:'Headcount & Staffing Plans',is_mandatory:true,considerations:'* Headcount planning & Projections\n* Talent Density & Specialization\n* Characteristics of work culture\n* Team structure\n* Sponsor from leadership to be identified\n* Communication plans with offshore teams',sort_order:5},
  {category:'Scale of Engineering Operations',driver_name:'Process, Structure & Well-Defined Roles',is_mandatory:true,considerations:'* Define and implement a process that is appropriate to the scale and complexity of the engineering operation\n* Evolve staffing strategies and well defined engineering roles as preparation to handle the additional scale.',sort_order:6},
  {category:'Scale of Engineering Operations',driver_name:'Leveraging Offshore Advantage',is_mandatory:true,considerations:'* Flexibility to scale the team and engineering operations as needed\n* Broader access to skilled talent across regions\n* Enhanced engineering capabilities through complementary benefits such as faster time-to-market and round-the-clock operations enabled by the offshore team',sort_order:7},
  {category:'Strategic Business Expansion',driver_name:'Centrally Located Engineering Operation',is_mandatory:true,considerations:'Either the complete engineering operation or at least the core of the engineering team is located in one main location.',sort_order:8},
  {category:'Strategic Business Expansion',driver_name:'Offshore Driven Strategic Expansion',is_mandatory:true,considerations:'When the product\'s business grows, challenges such as talent availability, geographic reach, and budget constraints may arise. These issues can be managed by relocating certain engineering operations to offshore locations.',sort_order:9},
];

export const BENCHMARK_TEMPLATE = [
  {pillar:'Operational Excellence',sub_category:'Performance / Product Stability',kpi_name:'Sprint Velocity',definition:'The average number of Story Points or work items a team completes per sprint. Goal is predictability over raw increase.',weight:0.1,unit:'pts/sprint',target_value:'±10% of Avg',sort_order:1},
  {pillar:'Operational Excellence',sub_category:'Performance / Product Stability',kpi_name:'Cycle Time',definition:'The time it takes for a work item to go from In Progress to Done.',weight:0.1,unit:'days',target_value:'≤ 4 days',sort_order:2},
  {pillar:'Operational Excellence',sub_category:'Performance / Product Stability',kpi_name:'Defect Escape Rate',definition:'The ratio of defects found in production to the total number of defects found. Goal is to find defects before release.',weight:0.1,unit:'%',target_value:'≤ 5%',sort_order:3},
  {pillar:'Operational Excellence',sub_category:'Performance / Product Stability',kpi_name:'Deployment Frequency',definition:'How often the team successfully releases changes to production.',weight:0.2,unit:'per week',target_value:'≥ 1/week',sort_order:4},
  {pillar:'Operational Excellence',sub_category:'Performance / Product Stability',kpi_name:'Code Maintainability Score',definition:'A score calculated by static analysis tools based on complexity, duplication, and coverage.',weight:0.1,unit:'score',target_value:'≥ 8/10',sort_order:5},
  {pillar:'Operational Excellence',sub_category:'Performance / Product Stability',kpi_name:'Change Failure Rate (CFR)',definition:'The percentage of deployments that result in a service impairment requiring remediation.',weight:0.2,unit:'%',target_value:'≤ 1%',sort_order:6},
  {pillar:'Operational Excellence',sub_category:'Performance / Product Stability',kpi_name:'Mean Time to Recovery (MTR)',definition:'The average time to restore service after a production incident.',weight:0.2,unit:'mins',target_value:'≤ 15 mins',sort_order:7},
  {pillar:'Operational Excellence',sub_category:'Commitment to AI and Automation for Efficiency',kpi_name:'Extent of AI Usage in coding and testing',definition:'The percentage of code/tests generated or refactored by AI tools compared to total.',weight:0.3,unit:'%',target_value:'≥ 25%',sort_order:8},
  {pillar:'Operational Excellence',sub_category:'Commitment to AI and Automation for Efficiency',kpi_name:'Effectiveness of QA Automation',definition:'The percentage of test coverage provided by automated tests and reduction in manual testing time.',weight:0.4,unit:'%',target_value:'≥ 85% Coverage',sort_order:9},
  {pillar:'Operational Excellence',sub_category:'Commitment to AI and Automation for Efficiency',kpi_name:'Success Rate of Release & Deployment Automation',definition:'The percentage of releases/deployments that complete automatically without manual intervention.',weight:0.3,unit:'%',target_value:'≥ 97%',sort_order:10},
  {pillar:'Operational Excellence',sub_category:'Continuous Improvement in Engineering Capabilities',kpi_name:'Progress Measured through Knowledge-Skill Matrix',definition:'The percentage increase in average skill level and critical skills covered by the team.',weight:0.3,unit:'%',target_value:'≥ 10% increase/qtr',sort_order:11},
  {pillar:'Operational Excellence',sub_category:'Continuous Improvement in Engineering Capabilities',kpi_name:'Optimal Resource Utilization',definition:'The percentage of engineer time spent on planned value-add work versus unplanned work.',weight:0.25,unit:'%',target_value:'≥ 95%',sort_order:12},
  {pillar:'Operational Excellence',sub_category:'Continuous Improvement in Engineering Capabilities',kpi_name:'Experimentation and Innovation Adoption',definition:'The number of prototypes, PoCs, or new technologies successfully integrated into production.',weight:0.2,unit:'count/qtr',target_value:'≥ 2/qtr',sort_order:13},
  {pillar:'Operational Excellence',sub_category:'Continuous Improvement in Engineering Capabilities',kpi_name:'Employee Retention Rates',definition:'The percentage of engineering staff retained over a 12-month period.',weight:0.25,unit:'%',target_value:'≥ 90%',sort_order:14},
  {pillar:'Operational Excellence',sub_category:'Quality of Work: Reliability and User Experience',kpi_name:'High System Availability',definition:'The percentage of time the system is operational and usable by customers.',weight:0.4,unit:'%',target_value:'≥ 99.95%',sort_order:15},
  {pillar:'Operational Excellence',sub_category:'Quality of Work: Reliability and User Experience',kpi_name:'Service-Level Objectives (SLOs)',definition:'Internal targets for measurable service characteristics (latency, throughput, error rate).',weight:0.35,unit:'%',target_value:'≥ 99%',sort_order:16},
  {pillar:'Operational Excellence',sub_category:'Quality of Work: Reliability and User Experience',kpi_name:'Customer Reported Incidents',definition:'The volume of unique, critical bugs or incidents reported by customers per month.',weight:0.25,unit:'count/month',target_value:'≤ 5/month',sort_order:17},
  {pillar:'Pace of Product Evolution',sub_category:'Speed and Efficiency of Product Development',kpi_name:'Release Cadence',definition:'How often a product or feature is deployed to the user environment.',weight:0.2,unit:'per month',target_value:'≥ 1/month',sort_order:18},
  {pillar:'Pace of Product Evolution',sub_category:'Speed and Efficiency of Product Development',kpi_name:'Cycle Time for New Features',definition:'The average time from first commit to production release for a feature.',weight:0.3,unit:'days',target_value:'≤ 4 days',sort_order:19},
  {pillar:'Pace of Product Evolution',sub_category:'Speed and Efficiency of Product Development',kpi_name:'Codebase Complexity Score (CCS)',definition:'An aggregate score (1-10) from static analysis of code cleanliness, test coverage, and architecture.',weight:0.2,unit:'score',target_value:'≥ 8/10',sort_order:20},
  {pillar:'Pace of Product Evolution',sub_category:'Speed and Efficiency of Product Development',kpi_name:'Rework Percentage',definition:'The percentage of work that must be reopened or revisited within the same dev cycle.',weight:0.15,unit:'%',target_value:'≤ 10%',sort_order:21},
  {pillar:'Pace of Product Evolution',sub_category:'Speed and Efficiency of Product Development',kpi_name:'Blocker Resolution Rate',definition:'The percentage of blocking issues resolved within a target time frame (e.g., 4 business hours).',weight:0.15,unit:'%',target_value:'≥ 95%',sort_order:22},
  {pillar:'Pace of Product Evolution',sub_category:'Roadmap Execution and Strategic Alignment',kpi_name:'Roadmap Adherence',definition:'The percentage of committed roadmap items completed within the targeted timeframe.',weight:0.3,unit:'%',target_value:'≥ 85%',sort_order:23},
  {pillar:'Pace of Product Evolution',sub_category:'Roadmap Execution and Strategic Alignment',kpi_name:'Feature Completion Rate',definition:'The percentage of features started and successfully completed within a sprint/period.',weight:0.25,unit:'%',target_value:'≥ 90%',sort_order:24},
  {pillar:'Pace of Product Evolution',sub_category:'Roadmap Execution and Strategic Alignment',kpi_name:'Lead Time for Changes',definition:'The time from first commit to running successfully in production (core DORA metric).',weight:0.35,unit:'days',target_value:'≤ 3 days',sort_order:25},
  {pillar:'Pace of Product Evolution',sub_category:'Roadmap Execution and Strategic Alignment',kpi_name:'Backlog Health',definition:'A score based on the percentage of backlog items that are sized, prioritized, and ready.',weight:0.1,unit:'%',target_value:'≥ 75% ready',sort_order:26},
  {pillar:'Pace of Product Evolution',sub_category:'Customer-Driven Innovation and Market Responsiveness',kpi_name:'Customer-Driven Enhancement Ratio',definition:'The percentage of new features originating from direct customer feedback or usage data.',weight:0.35,unit:'%',target_value:'≥ 65%',sort_order:27},
  {pillar:'Pace of Product Evolution',sub_category:'Customer-Driven Innovation and Market Responsiveness',kpi_name:'Customer Satisfaction with New Features',definition:'A score measuring customer happiness with recently released features.',weight:0.4,unit:'score',target_value:'≥ 8.5/10',sort_order:28},
  {pillar:'Pace of Product Evolution',sub_category:'Customer-Driven Innovation and Market Responsiveness',kpi_name:'Beta Feature Adoption Rate',definition:'The percentage of eligible users who actively engage with a new feature during beta testing.',weight:0.25,unit:'%',target_value:'≥ 15%',sort_order:29},
  {pillar:'Alignment',sub_category:'Cross Team Collaboration Efficiency',kpi_name:'Engineering-to-Product Alignment Score',definition:'A survey score on how well engineering roadmap aligns with product vision and business goals.',weight:0.15,unit:'score',target_value:'≥ 4.5/5',sort_order:30},
  {pillar:'Alignment',sub_category:'Cross Team Collaboration Efficiency',kpi_name:'Cross-Team Dependency Resolution Time',definition:'The average time to resolve an issue requiring input from two or more teams.',weight:0.25,unit:'days',target_value:'≤ 2 days',sort_order:31},
  {pillar:'Alignment',sub_category:'Cross Team Collaboration Efficiency',kpi_name:'Decision-Making Speed for Feature Approvals',definition:'The average time from feature proposal to final Go/No-Go approval.',weight:0.2,unit:'days',target_value:'≤ 3 days',sort_order:32},
  {pillar:'Alignment',sub_category:'Cross Team Collaboration Efficiency',kpi_name:'Stakeholder Satisfaction Scores',definition:'An aggregate score from key stakeholders on effectiveness of collaboration.',weight:0.15,unit:'score',target_value:'≥ 4.0/5',sort_order:33},
  {pillar:'Alignment',sub_category:'Cross Team Collaboration Efficiency',kpi_name:'Collaboration Frequency',definition:'The average number of value-driving interactions between team members and stakeholders per week.',weight:0.1,unit:'per week',target_value:'≥ 5/week',sort_order:34},
  {pillar:'Alignment',sub_category:'Cross Team Collaboration Efficiency',kpi_name:'Alignment with Shared OKRs',definition:'The percentage of shared objectives successfully met at end of cycle.',weight:0.15,unit:'%',target_value:'≥ 80%',sort_order:35},
  {pillar:'Alignment',sub_category:'Assessing Responsiveness and Adaptability',kpi_name:'Cycle Time for Decision-Making',definition:'The average time from identifying the need for a major decision to making and communicating it.',weight:0.4,unit:'days',target_value:'≤ 2 days',sort_order:36},
  {pillar:'Alignment',sub_category:'Assessing Responsiveness and Adaptability',kpi_name:'Roadmap Commitment Fulfilment',definition:'The percentage of work planned for a period that is successfully delivered.',weight:0.35,unit:'%',target_value:'≥ 85%',sort_order:37},
  {pillar:'Alignment',sub_category:'Assessing Responsiveness and Adaptability',kpi_name:'Feedback Incorporation Rates',definition:'The percentage of validated feedback added to the backlog and scheduled for implementation.',weight:0.25,unit:'%',target_value:'≥ 70%',sort_order:38},
  {pillar:'Alignment',sub_category:'Evaluating Engagement and Operational Cohesion',kpi_name:'Engagement in Cross-Functional Initiatives',definition:'Percentage of engineering team members actively contributing to shared non-feature work.',weight:0.25,unit:'%',target_value:'≥ 40%',sort_order:39},
  {pillar:'Alignment',sub_category:'Evaluating Engagement and Operational Cohesion',kpi_name:'Vendor Performance Ratings',definition:'An aggregate score on quality, timeliness, and cost-effectiveness of vendor work.',weight:0.25,unit:'score',target_value:'≥ 4.5/5',sort_order:40},
  {pillar:'Alignment',sub_category:'Evaluating Engagement and Operational Cohesion',kpi_name:'Net Promoter Score (NPS) for Internal Collaboration',definition:'NPS from internal stakeholders on how likely they are to recommend working with Engineering.',weight:0.5,unit:'score',target_value:'≥ 50',sort_order:41},
  {pillar:'Business Results Focused',sub_category:'Measuring Engineering-Driven Business Growth',kpi_name:'Percentage of New Features with Positive ROI',definition:'The percentage of features released in the last 12-18 months showing positive financial return.',weight:0.25,unit:'%',target_value:'≥ 70%',sort_order:42},
  {pillar:'Business Results Focused',sub_category:'Measuring Engineering-Driven Business Growth',kpi_name:'Business Impact of New Product Innovations',definition:'The percentage of revenue or profit derived from features released in the last 12-18 months.',weight:0.1,unit:'%',target_value:'≥ 25%',sort_order:43},
  {pillar:'Business Results Focused',sub_category:'Measuring Engineering-Driven Business Growth',kpi_name:'Feature Adoption Rate',definition:'The percentage of target users that use a new feature at least once within a defined period.',weight:0.1,unit:'%',target_value:'≥ 40%',sort_order:44},
  {pillar:'Business Results Focused',sub_category:'Measuring Engineering-Driven Business Growth',kpi_name:'Customer Retention Impact',definition:'The correlation between usage of new features and retention rate of customer cohorts.',weight:0.2,unit:'%',target_value:'≥ 5% higher retention',sort_order:45},
  {pillar:'Business Results Focused',sub_category:'Measuring Engineering-Driven Business Growth',kpi_name:'Cost Savings from Automation and Process Optimizations',definition:'The annualized dollar amount saved due to internal engineering efforts.',weight:0.1,unit:'USD/year',target_value:'≥ $100k/year',sort_order:46},
  {pillar:'Business Results Focused',sub_category:'Measuring Engineering-Driven Business Growth',kpi_name:'Cost of Quality (COQ)',definition:'The total cost as percentage of engineering spend on Prevention + Appraisal + Failure.',weight:0.15,unit:'%',target_value:'≤ 15% of spend',sort_order:47},
  {pillar:'Business Results Focused',sub_category:'Measuring Engineering-Driven Business Growth',kpi_name:'Technical Debt Ratio (TDR)',definition:'The percentage of time spent on planned maintenance and refactoring vs. new feature development.',weight:0.1,unit:'%',target_value:'≥ 20%',sort_order:48},
  {pillar:'Business Results Focused',sub_category:'Impact on Customers / End Users',kpi_name:'Time-to-Value (TTV)',definition:'The average time from feature release to when customers realize its core benefit.',weight:0.3,unit:'days',target_value:'≤ 2 days',sort_order:49},
  {pillar:'Business Results Focused',sub_category:'Impact on Customers / End Users',kpi_name:'Customer Commitment Success Rate',definition:'The percentage of major features delivered meeting the original agreed-upon deadline.',weight:0.25,unit:'%',target_value:'≥ 90%',sort_order:50},
  {pillar:'Business Results Focused',sub_category:'Impact on Customers / End Users',kpi_name:'Customer Satisfaction Score',definition:'The overall CSAT or NPS result from customer surveys.',weight:0.25,unit:'score',target_value:'≥ 8.5/10',sort_order:51},
  {pillar:'Business Results Focused',sub_category:'Impact on Customers / End Users',kpi_name:'Feature Stickiness / Health Score',definition:'The percentage of users who use a new feature more than three times in a given period.',weight:0.2,unit:'%',target_value:'≥ 15%',sort_order:52},
];

export const SCOPE_TEMPLATE = [
  {pillar:'Product Enhancement & Sustenance',activity:'Feature Development',required_level:2,l1_guidance:'The parent organization needs to provide detailed requirements for the features and also provide closer oversight to monitor execution.',l2_guidance:'The team designs and delivers complete features from high-level requirements with minimal supervision.',l3_guidance:'The team co-owns the responsibility to conceptualize the product in collaboration with internal and external stakeholders.',sort_order:1},
  {pillar:'Product Enhancement & Sustenance',activity:'Product Maintenance',required_level:3,l1_guidance:'The team will be responsible for reactive activities such as L1/L2/L3 support and fix minor defects.',l2_guidance:'The team is capable to analyze complex product issues and prepare proactive plans to make patches/releases.',l3_guidance:'Lead definition of patch and maintenance releases by prioritizing defects, technical, and feature debt. Manage all customer escalations.',sort_order:2},
  {pillar:'Product Enhancement & Sustenance',activity:'Solution Architecture, Deployment and Operations',required_level:3,l1_guidance:'Focus on operational aspects such as devops, database administration, cloud deployment, integration and scheduled maintenance.',l2_guidance:'The team monitors operational metrics and takes proactive steps to ensure the product meets functional and reliability targets.',l3_guidance:'Design architecture for global or regional deployments, including any negotiations with third-party providers for solution components.',sort_order:3},
  {pillar:'Product Enhancement & Sustenance',activity:'Professional Services',required_level:3,l1_guidance:'Work behind the scenes to make product configuration as per requirement provided by the parent organization.',l2_guidance:'The team will interact with customers to document the requirements, prepare the rollout plan and independently deliver any customizations.',l3_guidance:'Participate across customer engagement cycle. This includes presales, consultation for customers, implementation and configuration services.',sort_order:4},
  {pillar:'Thought Leadership',activity:'Measurable Effect on Business Outcome',required_level:2,l1_guidance:'The team is not expected to make any direct impact on business outcomes, except for offering operational cost advantage.',l2_guidance:'The team will own responsibilities that will directly impact product revenue cycles by delivering predictable results with minimal management oversight.',l3_guidance:'The team is active across the entire product lifecycle (including marketing and sales) to support efforts to create and sustain revenue streams.',sort_order:5},
  {pillar:'Thought Leadership',activity:'Product Roadmap - Feedback Loop',required_level:2,l1_guidance:'Support collection of data regarding product defects and operational challenges, which then supports decision-making by leadership team.',l2_guidance:'The team plays a critical role in managing requirements backlog (defects, technical debt, and feature debt) and ideas for incremental innovation.',l3_guidance:'Identify and prioritize release candidates by collaborating with internal and external stakeholders to ensure they align with business priorities.',sort_order:6},
  {pillar:'Thought Leadership',activity:'Culture of Excellence',required_level:3,l1_guidance:'Demonstrates the technical skills required to complete assigned engineering tasks and apply established best practices as directed.',l2_guidance:'Equipped with a product mindset, domain expertise, and technical skills, the team is able to deliver the product with very minimal guidance.',l3_guidance:'Demonstrates leadership skills to manage the full product lifecycle, represents the organization externally and publish whitepapers.',sort_order:7},
  {pillar:'Thought Leadership',activity:'Improve Customer Satisfaction',required_level:3,l1_guidance:'There is no direct impact on customer satisfaction. They can reduce the chance of dissatisfaction stemming from bugs or missed deadlines.',l2_guidance:'The team will ensure the product\'s features and its performance will offer the business advantages that end users expect.',l3_guidance:'Proactively identify and adopt new domain trends and evolving technology to ensure product remains highly relevant to customers.',sort_order:8},
  {pillar:'Business Result Focused',activity:'Impact on Business Profitability',required_level:2,l1_guidance:'Operational cost advantage will impact the bottomline, despite the additional bandwidth required for management oversight.',l2_guidance:'By reducing total cost of product ownership (TCO), the team offers significant bottom line advantage to improve profitability.',l3_guidance:'The team will play a key role in ensuring maximum ROI from investment in engineering efforts including feature development or ongoing R&D effort.',sort_order:9},
  {pillar:'Business Result Focused',activity:'Higher Share of Market',required_level:2,l1_guidance:'The team cannot be expected offer any advantage in terms of supporting the product\'s market share.',l2_guidance:'The team can support growth of the business by improving the time to market advantages.',l3_guidance:'Beyond core engineering, the team will leverage industry and customer insights to develop superior product capabilities that capture market share.',sort_order:10},
  {pillar:'Business Result Focused',activity:'Higher Customer Satisfaction',required_level:3,l1_guidance:'Disciplined execution and strict adherence to the engineering process will ensure consistent and high-quality deliverables.',l2_guidance:'Beyond delivering defect-free products, the team will ensure the product serves the intended business purpose of the end user.',l3_guidance:'Provide valuable consulting to customers and end users, regarding how the product can be leveraged to enhance or optimize the business.',sort_order:11},
  {pillar:'Customer Satisfaction',activity:'Incremental Innovations',required_level:2,l1_guidance:'There is no contribution expected in this regard.',l2_guidance:'The knowledge gained from product release cycles and operational issues should enable the team to generate ideas for incremental innovation.',l3_guidance:'Leveraging domain insights and customer feedback, the team owns responsibility to identify and prioritize new features for the product.',sort_order:12},
  {pillar:'Customer Satisfaction',activity:'Deliver Fully Functional Product',required_level:3,l1_guidance:'The team is limited to delivering to the specification provided by the product leadership team.',l2_guidance:'The team is responsible for ensuring the implemented features meet end-user needs and achieve the desired business benefits.',l3_guidance:'The team delivers product\'s long-term vision through iterative releases. The team will go beyond software to deliver tools like manuals and user-training.',sort_order:13},
  {pillar:'Customer Satisfaction',activity:'Rigour of QA Process',required_level:2,l1_guidance:'The team will largely focus on functional testing and regression cycles — as mandated by the QA strategy drafted by the parent organization.',l2_guidance:'The team develops its QA strategy and ensures a high-quality product across all aspects, including usability, operational stability, and performance.',l3_guidance:'The team identifies product shortcomings to define and remediate technical and feature debt, ensuring ongoing market and customer relevance.',sort_order:14},
  {pillar:'High Performance Talent',activity:'Inclusive & Growth Focused Work Culture',required_level:2,l1_guidance:'The growth path will focus on deepening technical mastery, process efficiency, and team leadership roles within product execution, support, and professional services.',l2_guidance:'Team members are provided opportunity to grow into world-class SMEs, Solution Architects, and senior technical roles with direct impact on system stability and TCO.',l3_guidance:'Growth focuses on business acumen, external thought leadership, and senior strategic leadership (VP/CXO) paths, tied directly to product success and market expansion.',sort_order:15},
  {pillar:'High Performance Talent',activity:'Benefits beyond Monetary Compensation',required_level:3,l1_guidance:'Investments are made so that the team members can constantly improve their technical skill, engineering process, and project stability.',l2_guidance:'The team members are provided learning opportunities in advanced systems design, domain depth, and consultative architecture. Benefits include specialized conferences.',l3_guidance:'The team receives benefits tied to business performance (e.g., profit-sharing, equity), executive coaching, and high visibility through customer interaction.',sort_order:16},
  {pillar:'High Performance Talent',activity:'Empowering Engineering Team Members',required_level:2,l1_guidance:'Focus on process transparency and communication integration into the daily routine. Feedback on tooling, process quality, and documentation is acted upon.',l2_guidance:'The team is granted architectural and design ownership and responsibility for defining technical requirements based on inputs from business leadership.',l3_guidance:'The team is included in product strategy, P&L discussions, and go-to-market decisions, apart from representing the company in industry forums.',sort_order:17},
];

export const LEADERSHIP_SKILLS = [
  {skill_category:'Technology & Domain',skill_name:'Software Development',is_mandatory:true,detailed_skills:'Full-stack proficiency, Performance tuning, Scalability patterns, DevOps/CI/CD pipelines, Cloud infrastructure (e.g., AWS/GCP)'},
  {skill_category:'Technology & Domain',skill_name:'Design Skill',is_mandatory:true,detailed_skills:'System Architecture, Microservices, API design (REST/GraphQL), Data modeling (SQL/NoSQL), Event-driven systems'},
  {skill_category:'Technology & Domain',skill_name:'Solution Architecture',is_mandatory:true,detailed_skills:'Cross-system integration, Security best practices, Resilience engineering, Observability setup (metrics, logging, tracing)'},
  {skill_category:'Technology & Domain',skill_name:'Ecosystem Health',is_mandatory:true,detailed_skills:'Dependency management, Tech stack auditing, Open-source software (OSS) licensing compliance, Security patching process'},
  {skill_category:'Technology & Domain',skill_name:'Product Operation',is_mandatory:true,detailed_skills:'On-call management, Incident response (P1/P2), Root Cause Analysis (RCA), Service Level Objectives (SLOs) definition'},
  {skill_category:'Technology & Domain',skill_name:'Experience with Domain',is_mandatory:true,detailed_skills:'Specific industry knowledge (e.g., FinTech, Logistics, Healthcare regulatory frameworks), Understanding user workflows'},
  {skill_category:'Technology & Domain',skill_name:'Security Governance',is_mandatory:true,detailed_skills:'Threat modeling, Defining security policies, Managing secrets, Implementing encryption standards, Vulnerability management'},
  {skill_category:'Technology & Domain',skill_name:'Regulatory Compliance',is_mandatory:true,detailed_skills:'GDPR, HIPAA, PCI-DSS compliance, Data retention policies, Implementing Privacy by Design, Audit response'},
  {skill_category:'Technology & Domain',skill_name:'Thought Leadership',is_mandatory:false,detailed_skills:'Presenting at industry conferences, Publishing white papers/blogs, Patent disclosures, Contributing to OSS'},
  {skill_category:'Project Execution',skill_name:'Product LifeCycle',is_mandatory:true,detailed_skills:'Idea inception to EOL planning, Technical debt management, Feature-toggle strategies, Release governance and rollback planning'},
  {skill_category:'Project Execution',skill_name:'Prioritize Backlog',is_mandatory:true,detailed_skills:'MoSCoW, RICE/WSJF scoring, Balancing feature work vs. technical debt vs. bug fixes, Capacity planning'},
  {skill_category:'Project Execution',skill_name:'Process Improvement',is_mandatory:true,detailed_skills:'Retrospective action tracking, Value Stream Mapping, Standardizing definitions of Done, Implementing automated quality gates'},
  {skill_category:'Project Execution',skill_name:'Estimation, Planning & Costing',is_mandatory:true,detailed_skills:'Agile methodologies (Scrum/Kanban), Story point/T-shirt sizing, OpEx/CapEx understanding, Resource allocation'},
  {skill_category:'Project Execution',skill_name:'Org Design & Structuring',is_mandatory:true,detailed_skills:'Defining team topologies, Determining optimal span of control, Managing organizational debt, Setting up remote/hybrid operating models'},
  {skill_category:'Project Execution',skill_name:'Vendor Management',is_mandatory:false,detailed_skills:'Contract negotiation, SLA monitoring, Managing external development teams/consultants, Software license renewals'},
  {skill_category:'Resourcefulness',skill_name:'Stakeholder Management',is_mandatory:true,detailed_skills:'Managing expectations across sales, marketing, finance, and peer engineering teams, Effective status communication'},
  {skill_category:'Resourcefulness',skill_name:'Customer Management',is_mandatory:true,detailed_skills:'Handling executive-level customer communication, Participating in pre-sales technical deep dives, Translating customer feedback'},
  {skill_category:'Resourcefulness',skill_name:'Escalation Handling',is_mandatory:true,detailed_skills:'Defining clear escalation paths, Making high-pressure decisions during crises, Post-mortem communication'},
  {skill_category:'Resourcefulness',skill_name:'Risk Management',is_mandatory:true,detailed_skills:'Identifying technical risks (dependency deprecation, security vulnerabilities, single points of failure) and mitigation planning'},
  {skill_category:'Resourcefulness',skill_name:'Industry Forum Representation',is_mandatory:false,detailed_skills:'Leading open-source projects, Sitting on standards committees, Networking with peer leaders (e.g., CTO forums)'},
  {skill_category:'Resourcefulness',skill_name:'Knowledge Sharing & Mentoring',is_mandatory:true,detailed_skills:'Establishing internal tech talks, Formal mentorship programs, Developing internal technical career ladders, Code review standards'},
  {skill_category:'Resourcefulness',skill_name:'Communication & Influence',is_mandatory:true,detailed_skills:'Technical presentation skills (to executive level), Cross-cultural communication, Active listening, Managing conflict resolution'},
  {skill_category:'Business Maturity',skill_name:'ROI from Investment in Engineering Effort',is_mandatory:true,detailed_skills:'Developing metrics to track engineering efficiency, Cost-benefit analysis for new technology adoption, Measuring customer impact'},
  {skill_category:'Business Maturity',skill_name:'Capitalize Team\'s Knowledge & Experience',is_mandatory:true,detailed_skills:'Developing internal documentation/wikis, Creating code sharing/review standards, Institutionalizing best practices into playbooks'},
  {skill_category:'Business Maturity',skill_name:'Intellectual Property (IP) Strategy',is_mandatory:false,detailed_skills:'Patent disclosure process, Protecting trade secrets, Freedom-to-Operate analysis, Competitive technical analysis'},
  {skill_category:'Business Maturity',skill_name:'Cultural Stewardship',is_mandatory:true,detailed_skills:'Fostering psychological safety, Defining core team values, Promoting a blameless culture, Driving DEI initiatives'},
  {skill_category:'Business Maturity',skill_name:'Strategic Finance',is_mandatory:true,detailed_skills:'Managing annual OpEx/CapEx budgets, Cloud cost management (FinOps), Forecasting engineering resource needs, Negotiating major contracts'},
  {skill_category:'Business Maturity',skill_name:'M&A Due Diligence',is_mandatory:false,detailed_skills:'Technical assessment of target companies, Integration/migration planning, Post-merger technology rationalization'},
  {skill_category:'Collaborative',skill_name:'Participate in Roadmap Planning',is_mandatory:true,detailed_skills:'Translating technical capabilities/limitations into product features, Influencing product strategy with technology trends'},
  {skill_category:'Collaborative',skill_name:'Presales Effort',is_mandatory:false,detailed_skills:'Providing technical validation for sales pitches, Drafting complex Statements of Work (SOWs), Technical solutioning for large clients'},
  {skill_category:'Collaborative',skill_name:'Talent Management & Development',is_mandatory:true,detailed_skills:'Hiring/Interviewing, Performance reviews, Career coaching, Succession planning, Defining job leveling'},
  {skill_category:'Collaborative',skill_name:'Cross-Functional Alignment',is_mandatory:true,detailed_skills:'Defining Service Level Agreements (SLAs) with Product/Operations, Negotiating resource dependencies, Facilitating joint planning'},
  {skill_category:'Collaborative',skill_name:'Conflict Resolution & Negotiation',is_mandatory:true,detailed_skills:'Mediating disagreements between technical and product vision, Negotiating timelines, Resolving interpersonal conflict'},
];

export const KRA_TEMPLATE = [
  {role_level:'Sr Director, Engineering/ VP',pillar:'Operational Excellence',kra_name:'High System Availability',sort_order:1},
  {role_level:'Sr Director, Engineering/ VP',pillar:'Pace of Product Evolution',kra_name:'Lead Time for Changes (Org-wide)',sort_order:2},
  {role_level:'Sr Director, Engineering/ VP',pillar:'Alignment',kra_name:'Stakeholder Alignment Score (Cross-Functional)',sort_order:3},
  {role_level:'Sr Director, Engineering/ VP',pillar:'Business Results Focused',kra_name:'Business Impact of New Product Innovations',sort_order:4},
  {role_level:'Sr Director, Engineering/ VP',pillar:'Operational Excellence',kra_name:'Cost of Quality (COQ)',sort_order:5},
  {role_level:'Sr Director, Engineering/ VP',pillar:'Pace of Product Evolution',kra_name:'Cycle Time for Decision-Making',sort_order:6},
  {role_level:'Sr Director, Engineering/ VP',pillar:'Alignment',kra_name:'Alignment with Shared OKRs',sort_order:7},
  {role_level:'Sr Director, Engineering/ VP',pillar:'Business Results Focused',kra_name:'Percentage of New Features with Positive ROI',sort_order:8},
  {role_level:'Senior Manager/ Director, Engineering',pillar:'Operational Excellence',kra_name:'Mean Time to Recovery (MTTR)',sort_order:9},
  {role_level:'Senior Manager/ Director, Engineering',pillar:'Pace of Product Evolution',kra_name:'Customer Commitment Success Rate',sort_order:10},
  {role_level:'Senior Manager/ Director, Engineering',pillar:'Alignment',kra_name:'Roadmap Adherence',sort_order:11},
  {role_level:'Senior Manager/ Director, Engineering',pillar:'Business Results Focused',kra_name:'Customer Retention Impact',sort_order:12},
  {role_level:'Senior Manager/ Director, Engineering',pillar:'Operational Excellence',kra_name:'Optimal Resource Utilization (Planned vs Unplanned)',sort_order:13},
  {role_level:'Senior Manager/ Director, Engineering',pillar:'Pace of Product Evolution',kra_name:'Technical Debt Ratio (TDR)',sort_order:14},
  {role_level:'Senior Manager/ Director, Engineering',pillar:'Alignment',kra_name:'Engineering-to-Product Alignment Score',sort_order:15},
  {role_level:'Senior Manager/ Director, Engineering',pillar:'Business Results Focused',kra_name:'Cost Savings from Automation',sort_order:16},
  {role_level:'Manager / Project Lead',pillar:'Operational Excellence',kra_name:'Change Failure Rate',sort_order:17},
  {role_level:'Manager / Project Lead',pillar:'Pace of Product Evolution',kra_name:'Cycle Time for New Features (Team-Level)',sort_order:18},
  {role_level:'Manager / Project Lead',pillar:'Alignment',kra_name:'Backlog Health',sort_order:19},
  {role_level:'Manager / Project Lead',pillar:'Business Results Focused',kra_name:'Roadmap Adherence and Customer Commitment',sort_order:20},
  {role_level:'Manager / Project Lead',pillar:'Operational Excellence',kra_name:'WIP Limits Adherence',sort_order:21},
  {role_level:'Manager / Project Lead',pillar:'Pace of Product Evolution',kra_name:'Cross-Team Dependency Resolution Time',sort_order:22},
  {role_level:'Manager / Project Lead',pillar:'Alignment',kra_name:'Feature Usage vs. Business Case %',sort_order:23},
  {role_level:'Manager / Project Lead',pillar:'Business Results Focused',kra_name:'Feature Adoption Rate',sort_order:24},
  {role_level:'Developer / Senior Developer',pillar:'Operational Excellence',kra_name:'Automated Test Coverage',sort_order:25},
  {role_level:'Developer / Senior Developer',pillar:'Pace of Product Evolution',kra_name:'Pull Request (PR) Merge Time',sort_order:26},
  {role_level:'Developer / Senior Developer',pillar:'Alignment',kra_name:'Code Review Response Time',sort_order:27},
  {role_level:'Developer / Senior Developer',pillar:'Business Results Focused',kra_name:'Feature Adoption and TTV',sort_order:28},
  {role_level:'Developer / Senior Developer',pillar:'Operational Excellence',kra_name:'Defect Escape Rate (Code/Component)',sort_order:29},
  {role_level:'Developer / Senior Developer',pillar:'Pace of Product Evolution',kra_name:'Time-to-Value (TTV)',sort_order:30},
  {role_level:'Developer / Senior Developer',pillar:'Alignment',kra_name:'Code Maintainability Score',sort_order:31},
  {role_level:'Developer / Senior Developer',pillar:'Business Results Focused',kra_name:'Feature Stickiness / Health Score',sort_order:32},
];

export const MATURITY_TEMPLATE = [
  {factor_name:'Product Enhancement & Maintenance',maturity_level:3,sort_order:1},
  {factor_name:'Thought Leadership',maturity_level:3,sort_order:2},
  {factor_name:'Business Result Focused',maturity_level:2,sort_order:3},
  {factor_name:'Customer Satisfaction',maturity_level:2,sort_order:4},
  {factor_name:'High Performance Talent',maturity_level:2,sort_order:5},
];
